# coding: utf-8

"""
    IGVF Catalog

    IGVF Catalog OpenAPI compliant REST API built using tRPC with Express.  Our database uses 0-based, half-open coordinates for genomic coordinates in the GRCh38 (human) and GRCm39 (mouse) reference genomes.  Data is licensed under the <a href=https://creativecommons.org/licenses/by/4.0/ target=\"_blank\">Creative Commons license</a> and the software is licensed under the <a href=https://spdx.org/licenses/MIT.html target=\"_blank\">MIT license</a>.

    The version of the OpenAPI document: 1.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from igvf_catalog_client.models.qtls3 import Qtls3

class TestQtls3(unittest.TestCase):
    """Qtls3 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Qtls3:
        """Test Qtls3
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Qtls3`
        """
        model = Qtls3()
        if include_optional:
            return Qtls3(
                type = '',
                cell_types = [
                    igvf_catalog_client.models.cell_types.CellTypes(
                        name = '', 
                        count = 1.337, )
                    ],
                genes = [
                    igvf_catalog_client.models.genes2.Genes2(
                        name = '', 
                        count = 1.337, )
                    ]
            )
        else:
            return Qtls3(
                type = '',
                cell_types = [
                    igvf_catalog_client.models.cell_types.CellTypes(
                        name = '', 
                        count = 1.337, )
                    ],
                genes = [
                    igvf_catalog_client.models.genes2.Genes2(
                        name = '', 
                        count = 1.337, )
                    ],
        )
        """

    def testQtls3(self):
        """Test Qtls3"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
