# coding: utf-8

"""
    IGVF Catalog

    IGVF Catalog OpenAPI compliant REST API built using tRPC with Express.  Our database uses 0-based, half-open coordinates for genomic coordinates in the GRCh38 (human) and GRCm39 (mouse) reference genomes.  Data is licensed under the <a href=https://creativecommons.org/licenses/by/4.0/ target=\"_blank\">Creative Commons license</a> and the software is licensed under the <a href=https://spdx.org/licenses/MIT.html target=\"_blank\">MIT license</a>.

    The version of the OpenAPI document: 1.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from igvf_catalog_client.models.phenotypes_from_variants200_response_inner_any_of1 import PhenotypesFromVariants200ResponseInnerAnyOf1

class TestPhenotypesFromVariants200ResponseInnerAnyOf1(unittest.TestCase):
    """PhenotypesFromVariants200ResponseInnerAnyOf1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PhenotypesFromVariants200ResponseInnerAnyOf1:
        """Test PhenotypesFromVariants200ResponseInnerAnyOf1
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PhenotypesFromVariants200ResponseInnerAnyOf1`
        """
        model = PhenotypesFromVariants200ResponseInnerAnyOf1()
        if include_optional:
            return PhenotypesFromVariants200ResponseInnerAnyOf1(
                name = '',
                biological_context = '',
                source = '',
                source_url = '',
                score = 1.337,
                effect_size = 1.337,
                z_score = 1.337,
                p_value = 1.337,
                neg_log10_pvalue = 1.337,
                significant = True,
                num_guides = 1.337,
                edit_rate_mean = 1.337,
                effect_size_ci95_lower = 1.337,
                effect_size_ci95_upper = 1.337,
                crispr_modality = '',
                method = '',
                var_class = '',
                label = '',
                files_filesets = '',
                biosample_term = '',
                phenotype_term = '',
                variant = None,
                phenotype_id = ''
            )
        else:
            return PhenotypesFromVariants200ResponseInnerAnyOf1(
                name = '',
                source = '',
                source_url = '',
                method = '',
                files_filesets = '',
                phenotype_term = '',
                variant = None,
                phenotype_id = '',
        )
        """

    def testPhenotypesFromVariants200ResponseInnerAnyOf1(self):
        """Test PhenotypesFromVariants200ResponseInnerAnyOf1"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
