# coding: utf-8

"""
    IGVF Catalog

    IGVF Catalog OpenAPI compliant REST API built using tRPC with Express.  Our database uses 0-based, half-open coordinates for genomic coordinates in the GRCh38 (human) and GRCm39 (mouse) reference genomes.  Data is licensed under the <a href=https://creativecommons.org/licenses/by/4.0/ target=\"_blank\">Creative Commons license</a> and the software is licensed under the <a href=https://spdx.org/licenses/MIT.html target=\"_blank\">MIT license</a>.

    The version of the OpenAPI document: 1.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from igvf_catalog_client.models.disease_from_variants200_response_inner_sequence_variant_any_of import DiseaseFromVariants200ResponseInnerSequenceVariantAnyOf

class TestDiseaseFromVariants200ResponseInnerSequenceVariantAnyOf(unittest.TestCase):
    """DiseaseFromVariants200ResponseInnerSequenceVariantAnyOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DiseaseFromVariants200ResponseInnerSequenceVariantAnyOf:
        """Test DiseaseFromVariants200ResponseInnerSequenceVariantAnyOf
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DiseaseFromVariants200ResponseInnerSequenceVariantAnyOf`
        """
        model = DiseaseFromVariants200ResponseInnerSequenceVariantAnyOf()
        if include_optional:
            return DiseaseFromVariants200ResponseInnerSequenceVariantAnyOf(
                chr = '',
                pos = 1.337,
                ref = '',
                alt = '',
                rsid = [
                    ''
                    ],
                spdi = '',
                hgvs = '',
                ca_id = ''
            )
        else:
            return DiseaseFromVariants200ResponseInnerSequenceVariantAnyOf(
                chr = '',
                pos = 1.337,
                ref = '',
                alt = '',
        )
        """

    def testDiseaseFromVariants200ResponseInnerSequenceVariantAnyOf(self):
        """Test DiseaseFromVariants200ResponseInnerSequenceVariantAnyOf"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
