# coding: utf-8

"""
    IGVF Catalog

    IGVF Catalog OpenAPI compliant REST API built using tRPC with Express.  Our database uses 0-based, half-open coordinates for genomic coordinates in the GRCh38 (human) and GRCm39 (mouse) reference genomes.  Data is licensed under the <a href=https://creativecommons.org/licenses/by/4.0/ target=\"_blank\">Creative Commons license</a> and the software is licensed under the <a href=https://spdx.org/licenses/MIT.html target=\"_blank\">MIT license</a>.

    The version of the OpenAPI document: 1.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from igvf_catalog_client.models.go_terms_from_annotations200_response_inner import GoTermsFromAnnotations200ResponseInner

class TestGoTermsFromAnnotations200ResponseInner(unittest.TestCase):
    """GoTermsFromAnnotations200ResponseInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GoTermsFromAnnotations200ResponseInner:
        """Test GoTermsFromAnnotations200ResponseInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GoTermsFromAnnotations200ResponseInner`
        """
        model = GoTermsFromAnnotations200ResponseInner()
        if include_optional:
            return GoTermsFromAnnotations200ResponseInner(
                gene_product_id = '',
                gene_product_name = '',
                go_term_name = '',
                source = '',
                gene_product_type = '',
                gene_product_symbol = '',
                qualifier = [
                    ''
                    ],
                organism = '',
                evidence = '',
                go_id = '',
                name = '',
                var_class = '',
                method = '',
                label = '',
                files_filesets = ''
            )
        else:
            return GoTermsFromAnnotations200ResponseInner(
                gene_product_id = '',
                go_term_name = '',
                source = '',
                gene_product_type = '',
                gene_product_symbol = '',
                qualifier = [
                    ''
                    ],
                organism = '',
                evidence = '',
                go_id = '',
                name = '',
        )
        """

    def testGoTermsFromAnnotations200ResponseInner(self):
        """Test GoTermsFromAnnotations200ResponseInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
