# coding: utf-8

"""
    IGVF Catalog

    IGVF Catalog OpenAPI compliant REST API built using tRPC with Express.  Our database uses 0-based, half-open coordinates for genomic coordinates in the GRCh38 (human) and GRCm39 (mouse) reference genomes.  Data is licensed under the <a href=https://creativecommons.org/licenses/by/4.0/ target=\"_blank\">Creative Commons license</a> and the software is licensed under the <a href=https://spdx.org/licenses/MIT.html target=\"_blank\">MIT license</a>.

    The version of the OpenAPI document: 1.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from igvf_catalog_client.models.phenotypes_from_variants200_response_inner_any_of import PhenotypesFromVariants200ResponseInnerAnyOf

class TestPhenotypesFromVariants200ResponseInnerAnyOf(unittest.TestCase):
    """PhenotypesFromVariants200ResponseInnerAnyOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PhenotypesFromVariants200ResponseInnerAnyOf:
        """Test PhenotypesFromVariants200ResponseInnerAnyOf
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PhenotypesFromVariants200ResponseInnerAnyOf`
        """
        model = PhenotypesFromVariants200ResponseInnerAnyOf()
        if include_optional:
            return PhenotypesFromVariants200ResponseInnerAnyOf(
                rsid = [
                    ''
                    ],
                phenotype_id = '',
                phenotype_term = '',
                study = None,
                neg_log10_pvalue = 1.337,
                p_value = 1.337,
                beta = 1.337,
                beta_ci_lower = 1.337,
                beta_ci_upper = 1.337,
                oddsr_ci_lower = 1.337,
                oddsr_ci_upper = 1.337,
                lead_chrom = '',
                lead_pos = 1.337,
                lead_ref = '',
                lead_alt = '',
                direction = '',
                source = 'OpenTargets',
                source_url = '',
                var_class = '',
                method = '',
                label = '',
                version = 'October 2022 (22.10)',
                name = '',
                variant = None,
                files_filesets = ''
            )
        else:
            return PhenotypesFromVariants200ResponseInnerAnyOf(
                phenotype_id = '',
                phenotype_term = '',
                p_value = 1.337,
                beta = 1.337,
                beta_ci_lower = 1.337,
                beta_ci_upper = 1.337,
                oddsr_ci_lower = 1.337,
                oddsr_ci_upper = 1.337,
                lead_chrom = '',
                lead_pos = 1.337,
                lead_ref = '',
                lead_alt = '',
                direction = '',
                source = 'OpenTargets',
                name = '',
                variant = None,
        )
        """

    def testPhenotypesFromVariants200ResponseInnerAnyOf(self):
        """Test PhenotypesFromVariants200ResponseInnerAnyOf"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
