# coding: utf-8

"""
    IGVF Catalog

    IGVF Catalog OpenAPI compliant REST API built using tRPC with Express.  Our database uses 0-based, half-open coordinates for genomic coordinates in the GRCh38 (human) and GRCm39 (mouse) reference genomes.  Data is licensed under the <a href=https://creativecommons.org/licenses/by/4.0/ target=\"_blank\">Creative Commons license</a> and the software is licensed under the <a href=https://spdx.org/licenses/MIT.html target=\"_blank\">MIT license</a>.

    The version of the OpenAPI document: 1.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from igvf_catalog_client.models.variants_from_variant_id200_response_inner import VariantsFromVariantID200ResponseInner

class TestVariantsFromVariantID200ResponseInner(unittest.TestCase):
    """VariantsFromVariantID200ResponseInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> VariantsFromVariantID200ResponseInner:
        """Test VariantsFromVariantID200ResponseInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `VariantsFromVariantID200ResponseInner`
        """
        model = VariantsFromVariantID200ResponseInner()
        if include_optional:
            return VariantsFromVariantID200ResponseInner(
                chr = '',
                ancestry = '',
                d_prime = 1.337,
                r2 = 1.337,
                label = '',
                variant_1_base_pair = '',
                variant_1_rsid = '',
                variant_2_base_pair = '',
                variant_2_rsid = '',
                variant_1_pos = 1.337,
                variant_1_spdi = '',
                variant_1_hgvs = '',
                variant_2_pos = 1.337,
                variant_2_spdi = '',
                variant_2_hgvs = '',
                source = '',
                source_url = '',
                sequence_variant = None,
                name = ''
            )
        else:
            return VariantsFromVariantID200ResponseInner(
                chr = '',
                ancestry = '',
                d_prime = 1.337,
                r2 = 1.337,
                label = '',
                variant_1_base_pair = '',
                variant_1_rsid = '',
                variant_2_base_pair = '',
                variant_2_rsid = '',
                name = '',
        )
        """

    def testVariantsFromVariantID200ResponseInner(self):
        """Test VariantsFromVariantID200ResponseInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
