# coding: utf-8

"""
    IGVF Catalog

    IGVF Catalog OpenAPI compliant REST API built using tRPC with Express.  Our database uses 0-based, half-open coordinates for genomic coordinates in the GRCh38 (human) and GRCm39 (mouse) reference genomes.  Data is licensed under the <a href=https://creativecommons.org/licenses/by/4.0/ target=\"_blank\">Creative Commons license</a> and the software is licensed under the <a href=https://spdx.org/licenses/MIT.html target=\"_blank\">MIT license</a>.

    The version of the OpenAPI document: 1.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from igvf_catalog_client.models.variant_summary200_response_nearest_genes_nearest_coding_gene import VariantSummary200ResponseNearestGenesNearestCodingGene

class TestVariantSummary200ResponseNearestGenesNearestCodingGene(unittest.TestCase):
    """VariantSummary200ResponseNearestGenesNearestCodingGene unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> VariantSummary200ResponseNearestGenesNearestCodingGene:
        """Test VariantSummary200ResponseNearestGenesNearestCodingGene
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `VariantSummary200ResponseNearestGenesNearestCodingGene`
        """
        model = VariantSummary200ResponseNearestGenesNearestCodingGene()
        if include_optional:
            return VariantSummary200ResponseNearestGenesNearestCodingGene(
                gene_name = '',
                id = '',
                start = 1.337,
                end = 1.337,
                distance = 1.337
            )
        else:
            return VariantSummary200ResponseNearestGenesNearestCodingGene(
                id = '',
                start = 1.337,
                end = 1.337,
                distance = 1.337,
        )
        """

    def testVariantSummary200ResponseNearestGenesNearestCodingGene(self):
        """Test VariantSummary200ResponseNearestGenesNearestCodingGene"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
