# coding: utf-8

"""
    IGVF Catalog

    IGVF Catalog OpenAPI compliant REST API built using tRPC with Express.  Our database uses 0-based, half-open coordinates for genomic coordinates in the GRCh38 (human) and GRCm39 (mouse) reference genomes.  Data is licensed under the <a href=https://creativecommons.org/licenses/by/4.0/ target=\"_blank\">Creative Commons license</a> and the software is licensed under the <a href=https://spdx.org/licenses/MIT.html target=\"_blank\">MIT license</a>.

    The version of the OpenAPI document: 1.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from igvf_catalog_client.models.phenotypes_from_coding_variants200_response_inner import PhenotypesFromCodingVariants200ResponseInner

class TestPhenotypesFromCodingVariants200ResponseInner(unittest.TestCase):
    """PhenotypesFromCodingVariants200ResponseInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PhenotypesFromCodingVariants200ResponseInner:
        """Test PhenotypesFromCodingVariants200ResponseInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PhenotypesFromCodingVariants200ResponseInner`
        """
        model = PhenotypesFromCodingVariants200ResponseInner()
        if include_optional:
            return PhenotypesFromCodingVariants200ResponseInner(
                coding_variant = igvf_catalog_client.models.phenotypes_from_coding_variants_200_response_inner_coding_variant.phenotypesFromCodingVariants_200_response_inner_coding_variant(
                    _id = '', 
                    aapos = 1.337, 
                    hgvsp = '', 
                    protein_name = '', 
                    gene_name = '', 
                    ref = '', 
                    alt = '', ),
                phenotype = igvf_catalog_client.models.phenotypes_from_coding_variants_200_response_inner_phenotype.phenotypesFromCodingVariants_200_response_inner_phenotype(
                    phenotype_id = '', 
                    phenotype_name = '', ),
                score = 1.337,
                method = '',
                var_class = '',
                label = '',
                files_filesets = '',
                source = '',
                source_url = '',
                variant = igvf_catalog_client.models.phenotypes_from_coding_variants_200_response_inner_variant.phenotypesFromCodingVariants_200_response_inner_variant(
                    chr = '', 
                    pos = 1.337, 
                    ref = '', 
                    alt = '', 
                    rsid = [
                        ''
                        ], 
                    spdi = '', 
                    hgvs = '', 
                    ca_id = '', 
                    _id = '', )
            )
        else:
            return PhenotypesFromCodingVariants200ResponseInner(
                score = 1.337,
                source = '',
                source_url = '',
        )
        """

    def testPhenotypesFromCodingVariants200ResponseInner(self):
        """Test PhenotypesFromCodingVariants200ResponseInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
