# coding: utf-8

"""
    IGVF Catalog

    IGVF Catalog OpenAPI compliant REST API built using tRPC with Express.  Our database uses 0-based, half-open coordinates for genomic coordinates in the GRCh38 (human) and GRCm39 (mouse) reference genomes.  Data is licensed under the <a href=https://creativecommons.org/licenses/by/4.0/ target=\"_blank\">Creative Commons license</a> and the software is licensed under the <a href=https://spdx.org/licenses/MIT.html target=\"_blank\">MIT license</a>.

    The version of the OpenAPI document: 1.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from igvf_catalog_client.models.coding_variants_from_variants200_response_inner import CodingVariantsFromVariants200ResponseInner

class TestCodingVariantsFromVariants200ResponseInner(unittest.TestCase):
    """CodingVariantsFromVariants200ResponseInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CodingVariantsFromVariants200ResponseInner:
        """Test CodingVariantsFromVariants200ResponseInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CodingVariantsFromVariants200ResponseInner`
        """
        model = CodingVariantsFromVariants200ResponseInner()
        if include_optional:
            return CodingVariantsFromVariants200ResponseInner(
                id = '',
                name = '',
                ref = '',
                alt = '',
                protein_name = '',
                protein_id = '',
                gene_name = '',
                transcript_id = '',
                aapos = 1.337,
                hgvsp = '',
                hgvsc = '',
                refcodon = '',
                codonpos = 1.337,
                sift_score = 1.337,
                sift4_g_score = 1.337,
                polyphen2_hdiv_score = 1.337,
                polyphen2_hvar_score = 1.337,
                vest4_score = 1.337,
                revel_score = 1.337,
                mut_pred_score = 1.337,
                bayes_del_add_af_score = 1.337,
                bayes_del_no_af_score = 1.337,
                varity_r_score = 1.337,
                varity_er_score = 1.337,
                varity_r_loo_score = 1.337,
                varity_er_loo_score = 1.337,
                esm1b_score = 1.337,
                alpha_missense_score = 1.337,
                cadd_raw_score = 1.337,
                source = '',
                source_url = ''
            )
        else:
            return CodingVariantsFromVariants200ResponseInner(
                id = '',
                name = '',
                ref = '',
                alt = '',
                protein_name = '',
                protein_id = '',
                gene_name = '',
                transcript_id = '',
                aapos = 1.337,
                hgvsp = '',
                refcodon = '',
                codonpos = 1.337,
                sift_score = 1.337,
                sift4_g_score = 1.337,
                polyphen2_hdiv_score = 1.337,
                polyphen2_hvar_score = 1.337,
                vest4_score = 1.337,
                revel_score = 1.337,
                mut_pred_score = 1.337,
                bayes_del_add_af_score = 1.337,
                bayes_del_no_af_score = 1.337,
                varity_r_score = 1.337,
                varity_er_score = 1.337,
                varity_r_loo_score = 1.337,
                varity_er_loo_score = 1.337,
                esm1b_score = 1.337,
                alpha_missense_score = 1.337,
                cadd_raw_score = 1.337,
                source = '',
                source_url = '',
        )
        """

    def testCodingVariantsFromVariants200ResponseInner(self):
        """Test CodingVariantsFromVariants200ResponseInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
