# coding: utf-8

"""
    IGVF Catalog

    IGVF Catalog OpenAPI compliant REST API built using tRPC with Express.  Our database uses 0-based, half-open coordinates for genomic coordinates in the GRCh38 (human) and GRCm39 (mouse) reference genomes.  Data is licensed under the <a href=https://creativecommons.org/licenses/by/4.0/ target=\"_blank\">Creative Commons license</a> and the software is licensed under the <a href=https://spdx.org/licenses/MIT.html target=\"_blank\">MIT license</a>.

    The version of the OpenAPI document: 1.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from igvf_catalog_client.models.proteins_from_variants200_response_inner import ProteinsFromVariants200ResponseInner

class TestProteinsFromVariants200ResponseInner(unittest.TestCase):
    """ProteinsFromVariants200ResponseInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProteinsFromVariants200ResponseInner:
        """Test ProteinsFromVariants200ResponseInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProteinsFromVariants200ResponseInner`
        """
        model = ProteinsFromVariants200ResponseInner()
        if include_optional:
            return ProteinsFromVariants200ResponseInner(
                sequence_variant = None,
                protein_complex = None,
                biosample_term = None,
                biological_context = '',
                regulatory_type = '',
                var_class = '',
                label = '',
                name = '',
                method = '',
                files_filesets = '',
                source = '',
                source_url = '',
                is_complex = True,
                score = 1.337,
                neg_log10_pvalue_adj_ref = 1.337,
                neg_log10_pvalue_adj_alt = 1.337,
                motif = '',
                motif_log2_fc = 1.337,
                beta = 1.337,
                se = 1.337,
                gene = '',
                gene_consequence = '',
                neg_log10_pvalue = 1.337,
                p_value = 1.337,
                neg_log10_pvalue_adj = 1.337,
                variant_effect_score = 1.337,
                se_mpl_annotation = '',
                se_mpl_baseline = 1.337,
                alt_score = 1.337,
                ref_score = 1.337,
                relative_binding_affinity = 1.337,
                effect_on_binding = ''
            )
        else:
            return ProteinsFromVariants200ResponseInner(
                name = '',
                is_complex = True,
        )
        """

    def testProteinsFromVariants200ResponseInner(self):
        """Test ProteinsFromVariants200ResponseInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
