# coding: utf-8

"""
    IGVF Catalog

    IGVF Catalog OpenAPI compliant REST API built using tRPC with Express.  Our database uses 0-based, half-open coordinates for genomic coordinates in the GRCh38 (human) and GRCm39 (mouse) reference genomes.  Data is licensed under the <a href=https://creativecommons.org/licenses/by/4.0/ target=\"_blank\">Creative Commons license</a> and the software is licensed under the <a href=https://spdx.org/licenses/MIT.html target=\"_blank\">MIT license</a>.

    The version of the OpenAPI document: 1.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from igvf_catalog_client.models.phenotypes_from_genomic_elements200_response_inner import PhenotypesFromGenomicElements200ResponseInner

class TestPhenotypesFromGenomicElements200ResponseInner(unittest.TestCase):
    """PhenotypesFromGenomicElements200ResponseInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PhenotypesFromGenomicElements200ResponseInner:
        """Test PhenotypesFromGenomicElements200ResponseInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PhenotypesFromGenomicElements200ResponseInner`
        """
        model = PhenotypesFromGenomicElements200ResponseInner()
        if include_optional:
            return PhenotypesFromGenomicElements200ResponseInner(
                name = '',
                label = '',
                method = '',
                var_class = '',
                source = '',
                source_url = '',
                biological_context = '',
                biosample_term = '',
                files_filesets = '',
                crispr_modality = '',
                z_score = 1.337,
                p_value = 1.337,
                neg_log10_pvalue = 1.337,
                significant = True,
                num_guides = 1.337,
                num_guides_hit = 1.337,
                num_guides_nonhit = 1.337,
                fraction_guides_hit = 1.337,
                phenotype_name = '',
                genomic_element = None,
                phenotype = None
            )
        else:
            return PhenotypesFromGenomicElements200ResponseInner(
                name = '',
                label = '',
                method = '',
                var_class = '',
                source = '',
                source_url = '',
                biological_context = '',
                biosample_term = '',
                files_filesets = '',
                genomic_element = None,
                phenotype = None,
        )
        """

    def testPhenotypesFromGenomicElements200ResponseInner(self):
        """Test PhenotypesFromGenomicElements200ResponseInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
