# coding: utf-8

"""
    IGVF Catalog

    IGVF Catalog OpenAPI compliant REST API built using tRPC with Express.  Our database uses 0-based, half-open coordinates for genomic coordinates in the GRCh38 (human) and GRCm39 (mouse) reference genomes.  Data is licensed under the <a href=https://creativecommons.org/licenses/by/4.0/ target=\"_blank\">Creative Commons license</a> and the software is licensed under the <a href=https://spdx.org/licenses/MIT.html target=\"_blank\">MIT license</a>.

    The version of the OpenAPI document: 1.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from igvf_catalog_client.models.genes_structure200_response_inner import GenesStructure200ResponseInner

class TestGenesStructure200ResponseInner(unittest.TestCase):
    """GenesStructure200ResponseInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GenesStructure200ResponseInner:
        """Test GenesStructure200ResponseInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GenesStructure200ResponseInner`
        """
        model = GenesStructure200ResponseInner()
        if include_optional:
            return GenesStructure200ResponseInner(
                id = '',
                name = '',
                chr = '',
                start = 1.337,
                end = 1.337,
                strand = '',
                type = '',
                gene_id = '',
                gene_name = '',
                transcript_id = '',
                transcript_name = '',
                protein_id = '',
                exon_number = '',
                exon_id = '',
                organism = '',
                source = '',
                version = '',
                source_url = ''
            )
        else:
            return GenesStructure200ResponseInner(
                id = '',
                name = '',
                chr = '',
                start = 1.337,
                end = 1.337,
                strand = '',
                type = '',
                gene_id = '',
                gene_name = '',
                transcript_id = '',
                transcript_name = '',
                exon_number = '',
                exon_id = '',
                organism = '',
                source = '',
                version = '',
                source_url = '',
        )
        """

    def testGenesStructure200ResponseInner(self):
        """Test GenesStructure200ResponseInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
