# coding: utf-8

"""
    IGVF Catalog

    IGVF Catalog OpenAPI compliant REST API built using tRPC with Express.  Our database uses 0-based, half-open coordinates for genomic coordinates in the GRCh38 (human) and GRCm39 (mouse) reference genomes.  Data is licensed under the <a href=https://creativecommons.org/licenses/by/4.0/ target=\"_blank\">Creative Commons license</a> and the software is licensed under the <a href=https://spdx.org/licenses/MIT.html target=\"_blank\">MIT license</a>.

    The version of the OpenAPI document: 1.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from igvf_catalog_client.models.genes_from_variants200_response_inner_study_any_of import GenesFromVariants200ResponseInnerStudyAnyOf

class TestGenesFromVariants200ResponseInnerStudyAnyOf(unittest.TestCase):
    """GenesFromVariants200ResponseInnerStudyAnyOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GenesFromVariants200ResponseInnerStudyAnyOf:
        """Test GenesFromVariants200ResponseInnerStudyAnyOf
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GenesFromVariants200ResponseInnerStudyAnyOf`
        """
        model = GenesFromVariants200ResponseInnerStudyAnyOf()
        if include_optional:
            return GenesFromVariants200ResponseInnerStudyAnyOf(
                id = '',
                name = '',
                ancestry_initial = '',
                ancestry_replication = '',
                n_cases = '',
                n_initial = '',
                n_replication = '',
                pmid = '',
                pub_author = '',
                pub_date = '',
                pub_journal = '',
                pub_title = '',
                has_sumstats = '',
                num_assoc_loci = '',
                study_source = '',
                trait_reported = '',
                trait_efos = '',
                trait_category = '',
                source = '',
                study_type = '',
                version = '',
                files_filesets = ''
            )
        else:
            return GenesFromVariants200ResponseInnerStudyAnyOf(
                id = '',
                name = '',
                ancestry_initial = '',
                ancestry_replication = '',
                n_cases = '',
                n_initial = '',
                n_replication = '',
                pmid = '',
                pub_author = '',
                pub_date = '',
                pub_journal = '',
                pub_title = '',
                has_sumstats = '',
                num_assoc_loci = '',
                study_source = '',
                trait_reported = '',
                trait_efos = '',
                trait_category = '',
                study_type = '',
                version = '',
        )
        """

    def testGenesFromVariants200ResponseInnerStudyAnyOf(self):
        """Test GenesFromVariants200ResponseInnerStudyAnyOf"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
