# coding: utf-8

"""
    IGVF Catalog

    IGVF Catalog OpenAPI compliant REST API built using tRPC with Express.  Our database uses 0-based, half-open coordinates for genomic coordinates in the GRCh38 (human) and GRCm39 (mouse) reference genomes.  Data is licensed under the <a href=https://creativecommons.org/licenses/by/4.0/ target=\"_blank\">Creative Commons license</a> and the software is licensed under the <a href=https://spdx.org/licenses/MIT.html target=\"_blank\">MIT license</a>.

    The version of the OpenAPI document: 1.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from igvf_catalog_client.models.variants_from_drugs200_response_inner import VariantsFromDrugs200ResponseInner

class TestVariantsFromDrugs200ResponseInner(unittest.TestCase):
    """VariantsFromDrugs200ResponseInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> VariantsFromDrugs200ResponseInner:
        """Test VariantsFromDrugs200ResponseInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `VariantsFromDrugs200ResponseInner`
        """
        model = VariantsFromDrugs200ResponseInner()
        if include_optional:
            return VariantsFromDrugs200ResponseInner(
                sequence_variant = None,
                to = '',
                gene_symbol = [
                    ''
                    ],
                pmid = '',
                study_parameters = [
                    igvf_catalog_client.models.drugs_from_variants_200_response_inner_study_parameters_inner.drugsFromVariants_200_response_inner_study_parameters_inner(
                        study_parameter_id = '', 
                        study_type = '', 
                        study_cases = '', 
                        study_controls = '', 
                        p_value = '', 
                        biogeographical_groups = '', )
                    ],
                phenotype_categories = [
                    ''
                    ],
                source = '',
                source_url = '',
                name = '',
                var_class = '',
                method = '',
                files_filesets = ''
            )
        else:
            return VariantsFromDrugs200ResponseInner(
                to = '',
                source = '',
                source_url = '',
                name = '',
        )
        """

    def testVariantsFromDrugs200ResponseInner(self):
        """Test VariantsFromDrugs200ResponseInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
