# coding: utf-8

"""
    IGVF Catalog

    IGVF Catalog OpenAPI compliant REST API built using tRPC with Express.  Our database uses 0-based, half-open coordinates for genomic coordinates in the GRCh38 (human) and GRCm39 (mouse) reference genomes.  Data is licensed under the <a href=https://creativecommons.org/licenses/by/4.0/ target=\"_blank\">Creative Commons license</a> and the software is licensed under the <a href=https://spdx.org/licenses/MIT.html target=\"_blank\">MIT license</a>.

    The version of the OpenAPI document: 1.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from igvf_catalog_client.models.drugs_from_variants200_response_inner import DrugsFromVariants200ResponseInner

class TestDrugsFromVariants200ResponseInner(unittest.TestCase):
    """DrugsFromVariants200ResponseInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DrugsFromVariants200ResponseInner:
        """Test DrugsFromVariants200ResponseInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DrugsFromVariants200ResponseInner`
        """
        model = DrugsFromVariants200ResponseInner()
        if include_optional:
            return DrugsFromVariants200ResponseInner(
                drug = None,
                var_from = '',
                gene_symbol = [
                    ''
                    ],
                pmid = '',
                study_parameters = [
                    igvf_catalog_client.models.drugs_from_variants_200_response_inner_study_parameters_inner.drugsFromVariants_200_response_inner_study_parameters_inner(
                        study_parameter_id = '', 
                        study_type = '', 
                        study_cases = '', 
                        study_controls = '', 
                        p_value = '', 
                        biogeographical_groups = '', )
                    ],
                phenotype_categories = [
                    ''
                    ],
                source = '',
                source_url = '',
                name = '',
                var_class = '',
                method = '',
                files_filesets = ''
            )
        else:
            return DrugsFromVariants200ResponseInner(
                var_from = '',
                source = '',
                source_url = '',
                name = '',
        )
        """

    def testDrugsFromVariants200ResponseInner(self):
        """Test DrugsFromVariants200ResponseInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
