# coding: utf-8

"""
    IGVF Catalog

    IGVF Catalog OpenAPI compliant REST API built using tRPC with Express.  Our database uses 0-based, half-open coordinates for genomic coordinates in the GRCh38 (human) and GRCm39 (mouse) reference genomes.  Data is licensed under the <a href=https://creativecommons.org/licenses/by/4.0/ target=\"_blank\">Creative Commons license</a> and the software is licensed under the <a href=https://spdx.org/licenses/MIT.html target=\"_blank\">MIT license</a>.

    The version of the OpenAPI document: 1.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from igvf_catalog_client.models.genes_proteins_from_variants import GenesProteinsFromVariants

class TestGenesProteinsFromVariants(unittest.TestCase):
    """GenesProteinsFromVariants unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GenesProteinsFromVariants:
        """Test GenesProteinsFromVariants
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GenesProteinsFromVariants`
        """
        model = GenesProteinsFromVariants()
        if include_optional:
            return GenesProteinsFromVariants(
                sequence_variant = igvf_catalog_client.models.sequence_variant9.SequenceVariant9(
                    _id = '', 
                    chr = '', 
                    pos = 1.337, 
                    rsid = [
                        ''
                        ], 
                    ref = '', 
                    alt = '', 
                    spdi = '', 
                    hgvs = '', 
                    ca_id = '', ),
                related = [
                    igvf_catalog_client.models.related.Related(
                        gene = null, 
                        protein = igvf_catalog_client.models.protein_compact.ProteinCompact(
                            _id = '', 
                            name = '', 
                            uniprot_names = [
                                ''
                                ], 
                            files_filesets = '', ), 
                        sources = null, )
                    ]
            )
        else:
            return GenesProteinsFromVariants(
                sequence_variant = igvf_catalog_client.models.sequence_variant9.SequenceVariant9(
                    _id = '', 
                    chr = '', 
                    pos = 1.337, 
                    rsid = [
                        ''
                        ], 
                    ref = '', 
                    alt = '', 
                    spdi = '', 
                    hgvs = '', 
                    ca_id = '', ),
                related = [
                    igvf_catalog_client.models.related.Related(
                        gene = null, 
                        protein = igvf_catalog_client.models.protein_compact.ProteinCompact(
                            _id = '', 
                            name = '', 
                            uniprot_names = [
                                ''
                                ], 
                            files_filesets = '', ), 
                        sources = null, )
                    ],
        )
        """

    def testGenesProteinsFromVariants(self):
        """Test GenesProteinsFromVariants"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
