# coding: utf-8

"""
    IGVF Catalog

    IGVF Catalog OpenAPI compliant REST API built using tRPC with Express.  Our database uses 0-based, half-open coordinates for genomic coordinates in the GRCh38 (human) and GRCm39 (mouse) reference genomes.  Data is licensed under the <a href=https://creativecommons.org/licenses/by/4.0/ target=\"_blank\">Creative Commons license</a> and the software is licensed under the <a href=https://spdx.org/licenses/MIT.html target=\"_blank\">MIT license</a>.

    The version of the OpenAPI document: 1.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from igvf_catalog_client.models.variants_from_phenotypes_item import VariantsFromPhenotypesItem

class TestVariantsFromPhenotypesItem(unittest.TestCase):
    """VariantsFromPhenotypesItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> VariantsFromPhenotypesItem:
        """Test VariantsFromPhenotypesItem
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `VariantsFromPhenotypesItem`
        """
        model = VariantsFromPhenotypesItem()
        if include_optional:
            return VariantsFromPhenotypesItem(
                rsid = [
                    ''
                    ],
                phenotype_id = '',
                phenotype_term = '',
                study = None,
                neg_log10_pvalue = 1.337,
                p_value = 1.337,
                beta = 1.337,
                beta_ci_lower = 1.337,
                beta_ci_upper = 1.337,
                oddsr_ci_lower = 1.337,
                oddsr_ci_upper = 1.337,
                lead_chrom = '',
                lead_pos = 1.337,
                lead_ref = '',
                lead_alt = '',
                direction = '',
                source = '',
                source_url = '',
                var_class = '',
                method = '',
                label = '',
                version = 'October 2022 (22.10)',
                name = '',
                variant = None,
                files_filesets = '',
                biological_context = '',
                score = 1.337,
                effect_size = 1.337,
                z_score = 1.337,
                significant = True,
                num_guides = 1.337,
                edit_rate_mean = 1.337,
                effect_size_ci95_lower = 1.337,
                effect_size_ci95_upper = 1.337,
                crispr_modality = '',
                biosample_term = ''
            )
        else:
            return VariantsFromPhenotypesItem(
                phenotype_id = '',
                phenotype_term = '',
                p_value = 1.337,
                beta = 1.337,
                beta_ci_lower = 1.337,
                beta_ci_upper = 1.337,
                oddsr_ci_lower = 1.337,
                oddsr_ci_upper = 1.337,
                lead_chrom = '',
                lead_pos = 1.337,
                lead_ref = '',
                lead_alt = '',
                direction = '',
                source = '',
                source_url = '',
                method = '',
                name = '',
                variant = None,
                files_filesets = '',
        )
        """

    def testVariantsFromPhenotypesItem(self):
        """Test VariantsFromPhenotypesItem"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
