# coding: utf-8

"""
    IGVF Catalog

    IGVF Catalog OpenAPI compliant REST API built using tRPC with Express.  Our database uses 0-based, half-open coordinates for genomic coordinates in the GRCh38 (human) and GRCm39 (mouse) reference genomes.  Data is licensed under the <a href=https://creativecommons.org/licenses/by/4.0/ target=\"_blank\">Creative Commons license</a> and the software is licensed under the <a href=https://spdx.org/licenses/MIT.html target=\"_blank\">MIT license</a>.

    The version of the OpenAPI document: 1.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from igvf_catalog_client.models.qtl_summary_endpoint200_response_inner import QtlSummaryEndpoint200ResponseInner

class TestQtlSummaryEndpoint200ResponseInner(unittest.TestCase):
    """QtlSummaryEndpoint200ResponseInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> QtlSummaryEndpoint200ResponseInner:
        """Test QtlSummaryEndpoint200ResponseInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `QtlSummaryEndpoint200ResponseInner`
        """
        model = QtlSummaryEndpoint200ResponseInner()
        if include_optional:
            return QtlSummaryEndpoint200ResponseInner(
                qtl_type = '',
                neg_log10_pvalue = 1.337,
                chr = '',
                biological_context = '',
                effect_size = 1.337,
                gene = igvf_catalog_client.models.qtl_summary_endpoint_200_response_inner_gene.qtlSummaryEndpoint_200_response_inner_gene(
                    gene_name = '', 
                    gene_id = '', 
                    gene_start = 1.337, 
                    gene_end = 1.337, ),
                name = '',
                files_filesets = ''
            )
        else:
            return QtlSummaryEndpoint200ResponseInner(
                qtl_type = '',
                chr = '',
        )
        """

    def testQtlSummaryEndpoint200ResponseInner(self):
        """Test QtlSummaryEndpoint200ResponseInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
