# coding: utf-8

"""
    IGVF Catalog

    IGVF Catalog OpenAPI compliant REST API built using tRPC with Express.  Our database uses 0-based, half-open coordinates for genomic coordinates in the GRCh38 (human) and GRCm39 (mouse) reference genomes.  Data is licensed under the <a href=https://creativecommons.org/licenses/by/4.0/ target=\"_blank\">Creative Commons license</a> and the software is licensed under the <a href=https://spdx.org/licenses/MIT.html target=\"_blank\">MIT license</a>.

    The version of the OpenAPI document: 1.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from igvf_catalog_client.models.variants_genomic_elements_genes200_response_inner import VariantsGenomicElementsGenes200ResponseInner

class TestVariantsGenomicElementsGenes200ResponseInner(unittest.TestCase):
    """VariantsGenomicElementsGenes200ResponseInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> VariantsGenomicElementsGenes200ResponseInner:
        """Test VariantsGenomicElementsGenes200ResponseInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `VariantsGenomicElementsGenes200ResponseInner`
        """
        model = VariantsGenomicElementsGenes200ResponseInner()
        if include_optional:
            return VariantsGenomicElementsGenes200ResponseInner(
                variant = igvf_catalog_client.models.proteins_from_variants_200_response_inner_sequence_variant_any_of.proteinsFromVariants_200_response_inner_sequence_variant_anyOf(
                    chr = '', 
                    pos = 1.337, 
                    ref = '', 
                    alt = '', 
                    rsid = [
                        ''
                        ], 
                    spdi = '', 
                    hgvs = '', 
                    ca_id = '', 
                    _id = '', ),
                distance_to_tss = 1.337,
                genomic_element = igvf_catalog_client.models.variants_genomic_elements_genes_200_response_inner_genomic_element.variantsGenomicElementsGenes_200_response_inner_genomic_element(
                    _id = '', 
                    name = '', 
                    chr = '', 
                    start = 1.337, 
                    end = 1.337, 
                    type = '', 
                    source = '', 
                    source_url = '', ),
                gene = igvf_catalog_client.models.variants_genomic_elements_genes_200_response_inner_gene.variantsGenomicElementsGenes_200_response_inner_gene(
                    _id = '', 
                    name = '', 
                    chr = '', 
                    start = 1.337, 
                    end = 1.337, 
                    strand = '', ),
                name = '',
                label = '',
                method = '',
                var_class = '',
                source = '',
                source_url = '',
                files_filesets = '',
                biological_context = '',
                biosample_term = '',
                crispr_modality = '',
                log2_fc = 1.337,
                neg_log10_pvalue = 1.337,
                neg_log10_pvalue_adj = None,
                p_value = None,
                p_value_adj = None,
                effect_size = 1.337,
                significant = True
            )
        else:
            return VariantsGenomicElementsGenes200ResponseInner(
                variant = igvf_catalog_client.models.proteins_from_variants_200_response_inner_sequence_variant_any_of.proteinsFromVariants_200_response_inner_sequence_variant_anyOf(
                    chr = '', 
                    pos = 1.337, 
                    ref = '', 
                    alt = '', 
                    rsid = [
                        ''
                        ], 
                    spdi = '', 
                    hgvs = '', 
                    ca_id = '', 
                    _id = '', ),
                genomic_element = igvf_catalog_client.models.variants_genomic_elements_genes_200_response_inner_genomic_element.variantsGenomicElementsGenes_200_response_inner_genomic_element(
                    _id = '', 
                    name = '', 
                    chr = '', 
                    start = 1.337, 
                    end = 1.337, 
                    type = '', 
                    source = '', 
                    source_url = '', ),
                gene = igvf_catalog_client.models.variants_genomic_elements_genes_200_response_inner_gene.variantsGenomicElementsGenes_200_response_inner_gene(
                    _id = '', 
                    name = '', 
                    chr = '', 
                    start = 1.337, 
                    end = 1.337, 
                    strand = '', ),
                name = '',
                label = '',
                method = '',
                var_class = '',
                source = '',
                source_url = '',
                files_filesets = '',
                biological_context = '',
                biosample_term = '',
        )
        """

    def testVariantsGenomicElementsGenes200ResponseInner(self):
        """Test VariantsGenomicElementsGenes200ResponseInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
