# coding: utf-8

"""
    IGVF Catalog

    IGVF Catalog OpenAPI compliant REST API built using tRPC with Express.  Our database uses 0-based, half-open coordinates for genomic coordinates in the GRCh38 (human) and GRCm39 (mouse) reference genomes.  Data is licensed under the <a href=https://creativecommons.org/licenses/by/4.0/ target=\"_blank\">Creative Commons license</a> and the software is licensed under the <a href=https://spdx.org/licenses/MIT.html target=\"_blank\">MIT license</a>.

    The version of the OpenAPI document: 1.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from igvf_catalog_client.models.pathways_from_genes200_response_inner_pathway import PathwaysFromGenes200ResponseInnerPathway

class TestPathwaysFromGenes200ResponseInnerPathway(unittest.TestCase):
    """PathwaysFromGenes200ResponseInnerPathway unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PathwaysFromGenes200ResponseInnerPathway:
        """Test PathwaysFromGenes200ResponseInnerPathway
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PathwaysFromGenes200ResponseInnerPathway`
        """
        model = PathwaysFromGenes200ResponseInnerPathway()
        if include_optional:
            return PathwaysFromGenes200ResponseInnerPathway(
                id = '',
                name = '',
                organism = '',
                source = '',
                source_url = '',
                id_version = '',
                is_in_disease = True,
                name_aliases = [
                    ''
                    ],
                is_top_level_pathway = True,
                disease_ontology_terms = [
                    ''
                    ],
                go_biological_process = '',
                var_class = '',
                method = '',
                label = '',
                files_filesets = ''
            )
        else:
            return PathwaysFromGenes200ResponseInnerPathway(
                id = '',
                name = '',
                organism = '',
                source = '',
                source_url = '',
                id_version = '',
                is_in_disease = True,
                name_aliases = [
                    ''
                    ],
                is_top_level_pathway = True,
                disease_ontology_terms = [
                    ''
                    ],
                go_biological_process = '',
                var_class = '',
                method = '',
                label = '',
                files_filesets = '',
        )
        """

    def testPathwaysFromGenes200ResponseInnerPathway(self):
        """Test PathwaysFromGenes200ResponseInnerPathway"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
