# coding: utf-8

"""
    IGVF Catalog

    IGVF Catalog OpenAPI compliant REST API built using tRPC with Express.  Our database uses 0-based, half-open coordinates for genomic coordinates in the GRCh38 (human) and GRCm39 (mouse) reference genomes.  Data is licensed under the <a href=https://creativecommons.org/licenses/by/4.0/ target=\"_blank\">Creative Commons license</a> and the software is licensed under the <a href=https://spdx.org/licenses/MIT.html target=\"_blank\">MIT license</a>.

    The version of the OpenAPI document: 1.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from igvf_catalog_client.models.diseases_from_genes import DiseasesFromGenes

class TestDiseasesFromGenes(unittest.TestCase):
    """DiseasesFromGenes unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DiseasesFromGenes:
        """Test DiseasesFromGenes
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DiseasesFromGenes`
        """
        model = DiseasesFromGenes()
        if include_optional:
            return DiseasesFromGenes(
                pmids = [
                    ''
                    ],
                term_name = '',
                gene_symbol = '',
                association_type = '',
                association_status = '',
                sgc_id = '',
                hgnc = '',
                classification = '',
                moi_id = '',
                moi_name = '',
                submitter = '',
                var_class = '',
                method = '',
                label = '',
                files_filesets = '',
                source = '',
                source_url = '',
                gene = None,
                disease = None,
                inheritance_mode = '',
                variants = [
                    igvf_catalog_client.models.variant_minimal.VariantMinimal(
                        chr = '', 
                        pos = 1.337, 
                        ref = '', 
                        alt = '', 
                        rsid = [
                            ''
                            ], 
                        spdi = '', 
                        hgvs = '', )
                    ],
                name = ''
            )
        else:
            return DiseasesFromGenes(
                name = '',
        )
        """

    def testDiseasesFromGenes(self):
        """Test DiseasesFromGenes"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
