# coding: utf-8

"""
    IGVF Catalog

    IGVF Catalog OpenAPI compliant REST API built using tRPC with Express.  Our database uses 0-based, half-open coordinates for genomic coordinates in the GRCh38 (human) and GRCm39 (mouse) reference genomes.  Data is licensed under the <a href=https://creativecommons.org/licenses/by/4.0/ target=\"_blank\">Creative Commons license</a> and the software is licensed under the <a href=https://spdx.org/licenses/MIT.html target=\"_blank\">MIT license</a>.

    The version of the OpenAPI document: 1.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from igvf_catalog_client.api.igvf_api import IgvfApi


class TestIgvfApi(unittest.TestCase):
    """IgvfApi unit test stubs"""

    def setUp(self) -> None:
        self.api = IgvfApi()

    def tearDown(self) -> None:
        pass

    def test_all_coding_variants_from_genes(self) -> None:
        """Test case for all_coding_variants_from_genes

        """
        pass

    def test_annotations_from_go_terms(self) -> None:
        """Test case for annotations_from_go_terms

        """
        pass

    def test_autocomplete(self) -> None:
        """Test case for autocomplete

        """
        pass

    def test_biosamples_from_genomic_elements(self) -> None:
        """Test case for biosamples_from_genomic_elements

        """
        pass

    def test_biosamples_from_variants(self) -> None:
        """Test case for biosamples_from_variants

        """
        pass

    def test_coding_variants(self) -> None:
        """Test case for coding_variants

        """
        pass

    def test_coding_variants_count_from_gene(self) -> None:
        """Test case for coding_variants_count_from_gene

        """
        pass

    def test_coding_variants_from_genes(self) -> None:
        """Test case for coding_variants_from_genes

        """
        pass

    def test_coding_variants_from_phenotypes(self) -> None:
        """Test case for coding_variants_from_phenotypes

        """
        pass

    def test_coding_variants_from_variants(self) -> None:
        """Test case for coding_variants_from_variants

        """
        pass

    def test_coding_variants_summary(self) -> None:
        """Test case for coding_variants_summary

        """
        pass

    def test_complexes(self) -> None:
        """Test case for complexes

        """
        pass

    def test_complexes_from_proteins(self) -> None:
        """Test case for complexes_from_proteins

        """
        pass

    def test_deprecated_coding_variants_summary(self) -> None:
        """Test case for deprecated_coding_variants_summary

        """
        pass

    def test_disease_from_variants(self) -> None:
        """Test case for disease_from_variants

        """
        pass

    def test_diseases_from_genes(self) -> None:
        """Test case for diseases_from_genes

        """
        pass

    def test_drugs(self) -> None:
        """Test case for drugs

        """
        pass

    def test_drugs_from_variants(self) -> None:
        """Test case for drugs_from_variants

        """
        pass

    def test_enhancer_gene_predictions(self) -> None:
        """Test case for enhancer_gene_predictions

        """
        pass

    def test_files_filesets(self) -> None:
        """Test case for files_filesets

        """
        pass

    def test_genes(self) -> None:
        """Test case for genes

        """
        pass

    def test_genes_from_diseases(self) -> None:
        """Test case for genes_from_diseases

        """
        pass

    def test_genes_from_genomic_elements(self) -> None:
        """Test case for genes_from_genomic_elements

        """
        pass

    def test_genes_from_pathways(self) -> None:
        """Test case for genes_from_pathways

        """
        pass

    def test_genes_from_proteins(self) -> None:
        """Test case for genes_from_proteins

        """
        pass

    def test_genes_from_transcripts(self) -> None:
        """Test case for genes_from_transcripts

        """
        pass

    def test_genes_from_variants(self) -> None:
        """Test case for genes_from_variants

        """
        pass

    def test_genes_genes(self) -> None:
        """Test case for genes_genes

        """
        pass

    def test_genes_proteins_from_variants(self) -> None:
        """Test case for genes_proteins_from_variants

        """
        pass

    def test_genes_proteins_genes_proteins(self) -> None:
        """Test case for genes_proteins_genes_proteins

        """
        pass

    def test_genes_structure(self) -> None:
        """Test case for genes_structure

        """
        pass

    def test_genomic_elements(self) -> None:
        """Test case for genomic_elements

        """
        pass

    def test_genomic_elements_from_biosamples(self) -> None:
        """Test case for genomic_elements_from_biosamples

        """
        pass

    def test_genomic_elements_from_genes(self) -> None:
        """Test case for genomic_elements_from_genes

        """
        pass

    def test_genomic_elements_from_phenotypes(self) -> None:
        """Test case for genomic_elements_from_phenotypes

        """
        pass

    def test_genomic_elements_from_variants(self) -> None:
        """Test case for genomic_elements_from_variants

        """
        pass

    def test_genomic_elements_from_variants_count(self) -> None:
        """Test case for genomic_elements_from_variants_count

        """
        pass

    def test_genomic_elements_predictions_from_variant(self) -> None:
        """Test case for genomic_elements_predictions_from_variant

        """
        pass

    def test_go_terms_from_annotations(self) -> None:
        """Test case for go_terms_from_annotations

        """
        pass

    def test_grn(self) -> None:
        """Test case for grn

        """
        pass

    def test_health(self) -> None:
        """Test case for health

        """
        pass

    def test_motifs(self) -> None:
        """Test case for motifs

        """
        pass

    def test_motifs_from_proteins(self) -> None:
        """Test case for motifs_from_proteins

        """
        pass

    def test_nearest_genes(self) -> None:
        """Test case for nearest_genes

        """
        pass

    def test_ontology_term(self) -> None:
        """Test case for ontology_term

        """
        pass

    def test_ontology_term_children(self) -> None:
        """Test case for ontology_term_children

        """
        pass

    def test_ontology_term_parents(self) -> None:
        """Test case for ontology_term_parents

        """
        pass

    def test_ontology_term_transitive_closure(self) -> None:
        """Test case for ontology_term_transitive_closure

        """
        pass

    def test_pathways(self) -> None:
        """Test case for pathways

        """
        pass

    def test_pathways_from_genes(self) -> None:
        """Test case for pathways_from_genes

        """
        pass

    def test_pathways_from_pathways(self) -> None:
        """Test case for pathways_from_pathways

        """
        pass

    def test_phenotypes_from_coding_variants(self) -> None:
        """Test case for phenotypes_from_coding_variants

        """
        pass

    def test_phenotypes_from_genomic_elements(self) -> None:
        """Test case for phenotypes_from_genomic_elements

        """
        pass

    def test_phenotypes_from_variants(self) -> None:
        """Test case for phenotypes_from_variants

        """
        pass

    def test_predictions_from_variants(self) -> None:
        """Test case for predictions_from_variants

        """
        pass

    def test_proteins(self) -> None:
        """Test case for proteins

        """
        pass

    def test_proteins_from_complexes(self) -> None:
        """Test case for proteins_from_complexes

        """
        pass

    def test_proteins_from_genes(self) -> None:
        """Test case for proteins_from_genes

        """
        pass

    def test_proteins_from_motifs(self) -> None:
        """Test case for proteins_from_motifs

        """
        pass

    def test_proteins_from_transcripts(self) -> None:
        """Test case for proteins_from_transcripts

        """
        pass

    def test_proteins_from_variants(self) -> None:
        """Test case for proteins_from_variants

        """
        pass

    def test_proteins_proteins(self) -> None:
        """Test case for proteins_proteins

        """
        pass

    def test_qtl_summary_endpoint(self) -> None:
        """Test case for qtl_summary_endpoint

        """
        pass

    def test_qtls(self) -> None:
        """Test case for qtls

        """
        pass

    def test_studies(self) -> None:
        """Test case for studies

        """
        pass

    def test_transcripts(self) -> None:
        """Test case for transcripts

        """
        pass

    def test_transcripts_from_genes(self) -> None:
        """Test case for transcripts_from_genes

        """
        pass

    def test_transcripts_from_proteins(self) -> None:
        """Test case for transcripts_from_proteins

        """
        pass

    def test_variant_by_frequency_source(self) -> None:
        """Test case for variant_by_frequency_source

        """
        pass

    def test_variant_summary(self) -> None:
        """Test case for variant_summary

        """
        pass

    def test_variants(self) -> None:
        """Test case for variants

        """
        pass

    def test_variants_alleles(self) -> None:
        """Test case for variants_alleles

        """
        pass

    def test_variants_from_biosamples(self) -> None:
        """Test case for variants_from_biosamples

        """
        pass

    def test_variants_from_coding_variants(self) -> None:
        """Test case for variants_from_coding_variants

        """
        pass

    def test_variants_from_diseases(self) -> None:
        """Test case for variants_from_diseases

        """
        pass

    def test_variants_from_drugs(self) -> None:
        """Test case for variants_from_drugs

        """
        pass

    def test_variants_from_gene_proteins(self) -> None:
        """Test case for variants_from_gene_proteins

        """
        pass

    def test_variants_from_genes(self) -> None:
        """Test case for variants_from_genes

        """
        pass

    def test_variants_from_genomic_elements(self) -> None:
        """Test case for variants_from_genomic_elements

        """
        pass

    def test_variants_from_phenotypes(self) -> None:
        """Test case for variants_from_phenotypes

        """
        pass

    def test_variants_from_proteins(self) -> None:
        """Test case for variants_from_proteins

        """
        pass

    def test_variants_from_variant_id(self) -> None:
        """Test case for variants_from_variant_id

        """
        pass

    def test_variants_from_variant_id_summary(self) -> None:
        """Test case for variants_from_variant_id_summary

        """
        pass

    def test_variants_genomic_elements_genes(self) -> None:
        """Test case for variants_genomic_elements_genes

        """
        pass

    def test_variants_region_summary(self) -> None:
        """Test case for variants_region_summary

        """
        pass


if __name__ == '__main__':
    unittest.main()
