# coding: utf-8

"""
    IGVF Catalog

    IGVF Catalog OpenAPI compliant REST API built using tRPC with Express.  Our database uses 0-based, half-open coordinates for genomic coordinates in the GRCh38 (human) and GRCm39 (mouse) reference genomes.  Data is licensed under the <a href=https://creativecommons.org/licenses/by/4.0/ target=\"_blank\">Creative Commons license</a> and the software is licensed under the <a href=https://spdx.org/licenses/MIT.html target=\"_blank\">MIT license</a>.

    The version of the OpenAPI document: 1.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from igvf_catalog_client.models.ontology_term_parents200_response_inner import OntologyTermParents200ResponseInner

class TestOntologyTermParents200ResponseInner(unittest.TestCase):
    """OntologyTermParents200ResponseInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OntologyTermParents200ResponseInner:
        """Test OntologyTermParents200ResponseInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OntologyTermParents200ResponseInner`
        """
        model = OntologyTermParents200ResponseInner()
        if include_optional:
            return OntologyTermParents200ResponseInner(
                term = igvf_catalog_client.models.proteins_from_variants_200_response_inner_biosample_term_any_of.proteinsFromVariants_200_response_inner_biosample_term_anyOf(
                    uri = '', 
                    term_id = '', 
                    name = '', 
                    synonyms = [
                        ''
                        ], 
                    description = '', 
                    source = '', 
                    subontology = '', 
                    source_url = '', 
                    class = '', 
                    method = '', 
                    files_filesets = '', ),
                relationship_type = ''
            )
        else:
            return OntologyTermParents200ResponseInner(
                term = igvf_catalog_client.models.proteins_from_variants_200_response_inner_biosample_term_any_of.proteinsFromVariants_200_response_inner_biosample_term_anyOf(
                    uri = '', 
                    term_id = '', 
                    name = '', 
                    synonyms = [
                        ''
                        ], 
                    description = '', 
                    source = '', 
                    subontology = '', 
                    source_url = '', 
                    class = '', 
                    method = '', 
                    files_filesets = '', ),
                relationship_type = '',
        )
        """

    def testOntologyTermParents200ResponseInner(self):
        """Test OntologyTermParents200ResponseInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
