# coding: utf-8

"""
    IGVF Catalog

    IGVF Catalog OpenAPI compliant REST API built using tRPC with Express.  Our database uses 0-based, half-open coordinates for genomic coordinates in the GRCh38 (human) and GRCm39 (mouse) reference genomes.  Data is licensed under the <a href=https://creativecommons.org/licenses/by/4.0/ target=\"_blank\">Creative Commons license</a> and the software is licensed under the <a href=https://spdx.org/licenses/MIT.html target=\"_blank\">MIT license</a>.

    The version of the OpenAPI document: 1.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from igvf_catalog_client.models.files_filesets import FilesFilesets

class TestFilesFilesets(unittest.TestCase):
    """FilesFilesets unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FilesFilesets:
        """Test FilesFilesets
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FilesFilesets`
        """
        model = FilesFilesets()
        if include_optional:
            return FilesFilesets(
                id = '',
                file_set_id = '',
                lab = '',
                preferred_assay_titles = [
                    ''
                    ],
                assay_term_ids = [
                    ''
                    ],
                method = '',
                var_class = '',
                software = [
                    ''
                    ],
                collections = [
                    ''
                    ],
                samples = [
                    ''
                    ],
                sample_ids = [
                    ''
                    ],
                simple_sample_summaries = [
                    ''
                    ],
                donors = [
                    ''
                    ],
                source = '',
                source_url = '',
                download_link = '',
                cell_annotation = '',
                cell_annotation_term = '',
                genome_browser_link = '',
                crispr_modality = ''
            )
        else:
            return FilesFilesets(
                id = '',
                file_set_id = '',
                lab = '',
                var_class = '',
                source = '',
                download_link = '',
        )
        """

    def testFilesFilesets(self):
        """Test FilesFilesets"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
