# coding: utf-8

"""
    IGVF Catalog

    IGVF Catalog OpenAPI compliant REST API built using tRPC with Express.  Our database uses 0-based, half-open coordinates for genomic coordinates in the GRCh38 (human) and GRCm39 (mouse) reference genomes.  Data is licensed under the <a href=https://creativecommons.org/licenses/by/4.0/ target=\"_blank\">Creative Commons license</a> and the software is licensed under the <a href=https://spdx.org/licenses/MIT.html target=\"_blank\">MIT license</a>.

    The version of the OpenAPI document: 1.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from igvf_catalog_client.models.grn import Grn

class TestGrn(unittest.TestCase):
    """Grn unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Grn:
        """Test Grn
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Grn`
        """
        model = Grn()
        if include_optional:
            return Grn(
                response_gene = '',
                genomic_element = igvf_catalog_client.models.genomic_element4.GenomicElement4(
                    chr = '', 
                    start = 1.337, 
                    end = 1.337, 
                    regulator_gene = '', ),
                crispr_modality = '',
                var_class = '',
                method = '',
                source = '',
                biological_context = '',
                files_filesets = '',
                log2_fc = 1.337,
                neg_log10_pvalue = None,
                neg_log10_pvalue_adj = None,
                significant = True,
                perturbation_efficiency_log2_fc = 1.337,
                perturbation_efficiency_neg_log10_pvalue = None,
                perturbation_efficiency_neg_log10_pvalue_adj = None,
                perturbation_efficiency_significant = True
            )
        else:
            return Grn(
                response_gene = '',
                genomic_element = igvf_catalog_client.models.genomic_element4.GenomicElement4(
                    chr = '', 
                    start = 1.337, 
                    end = 1.337, 
                    regulator_gene = '', ),
                var_class = '',
                method = '',
                source = '',
                biological_context = '',
                files_filesets = '',
        )
        """

    def testGrn(self):
        """Test Grn"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
