# coding: utf-8

"""
    IGVF Catalog

    IGVF Catalog OpenAPI compliant REST API built using tRPC with Express.  Our database uses 0-based, half-open coordinates for genomic coordinates in the GRCh38 (human) and GRCm39 (mouse) reference genomes.  Data is licensed under the <a href=https://creativecommons.org/licenses/by/4.0/ target=\"_blank\">Creative Commons license</a> and the software is licensed under the <a href=https://spdx.org/licenses/MIT.html target=\"_blank\">MIT license</a>.

    The version of the OpenAPI document: 1.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from igvf_catalog_client.models.complexes_from_proteins import ComplexesFromProteins

class TestComplexesFromProteins(unittest.TestCase):
    """ComplexesFromProteins unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ComplexesFromProteins:
        """Test ComplexesFromProteins
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ComplexesFromProteins`
        """
        model = ComplexesFromProteins()
        if include_optional:
            return ComplexesFromProteins(
                protein = None,
                complex = None,
                name = '',
                stoichiometry = 1.337,
                chain_id = '',
                isoform_id = '',
                number_of_paralogs = 1.337,
                linked_features = [
                    igvf_catalog_client.models.linked_feature.LinkedFeature(
                        participant_id = '', 
                        ranges = [
                            ''
                            ], )
                    ],
                var_class = '',
                method = '',
                label = '',
                files_filesets = '',
                source = '',
                source_url = ''
            )
        else:
            return ComplexesFromProteins(
                name = '',
                method = '',
                label = '',
        )
        """

    def testComplexesFromProteins(self):
        """Test ComplexesFromProteins"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
