# coding: utf-8

"""
    IGVF Catalog

    IGVF Catalog OpenAPI compliant REST API built using tRPC with Express.  Our database uses 0-based, half-open coordinates for genomic coordinates in the GRCh38 (human) and GRCm39 (mouse) reference genomes.  Data is licensed under the <a href=https://creativecommons.org/licenses/by/4.0/ target=\"_blank\">Creative Commons license</a> and the software is licensed under the <a href=https://spdx.org/licenses/MIT.html target=\"_blank\">MIT license</a>.

    The version of the OpenAPI document: 1.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from igvf_catalog_client.models.variants_genomic_elements_genes200_response_inner_gene import VariantsGenomicElementsGenes200ResponseInnerGene

class TestVariantsGenomicElementsGenes200ResponseInnerGene(unittest.TestCase):
    """VariantsGenomicElementsGenes200ResponseInnerGene unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> VariantsGenomicElementsGenes200ResponseInnerGene:
        """Test VariantsGenomicElementsGenes200ResponseInnerGene
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `VariantsGenomicElementsGenes200ResponseInnerGene`
        """
        model = VariantsGenomicElementsGenes200ResponseInnerGene()
        if include_optional:
            return VariantsGenomicElementsGenes200ResponseInnerGene(
                id = '',
                name = '',
                chr = '',
                start = 1.337,
                end = 1.337,
                strand = ''
            )
        else:
            return VariantsGenomicElementsGenes200ResponseInnerGene(
                id = '',
                name = '',
                chr = '',
                start = 1.337,
                end = 1.337,
        )
        """

    def testVariantsGenomicElementsGenes200ResponseInnerGene(self):
        """Test VariantsGenomicElementsGenes200ResponseInnerGene"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
