# coding: utf-8

"""
    IGVF Catalog

    IGVF Catalog OpenAPI compliant REST API built using tRPC with Express.  Our database uses 0-based, half-open coordinates for genomic coordinates in the GRCh38 (human) and GRCm39 (mouse) reference genomes.  Data is licensed under the <a href=https://creativecommons.org/licenses/by/4.0/ target=\"_blank\">Creative Commons license</a> and the software is licensed under the <a href=https://spdx.org/licenses/MIT.html target=\"_blank\">MIT license</a>.

    The version of the OpenAPI document: 1.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from igvf_catalog_client.models.transcripts_from_genes200_response_inner_transcript import TranscriptsFromGenes200ResponseInnerTranscript

class TestTranscriptsFromGenes200ResponseInnerTranscript(unittest.TestCase):
    """TranscriptsFromGenes200ResponseInnerTranscript unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TranscriptsFromGenes200ResponseInnerTranscript:
        """Test TranscriptsFromGenes200ResponseInnerTranscript
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TranscriptsFromGenes200ResponseInnerTranscript`
        """
        model = TranscriptsFromGenes200ResponseInnerTranscript()
        if include_optional:
            return TranscriptsFromGenes200ResponseInnerTranscript(
                id = '',
                transcript_type = '',
                chr = '',
                start = 1.337,
                end = 1.337,
                strand = '',
                name = '',
                gene_name = '',
                mane_select = True,
                source = '',
                version = '',
                source_url = ''
            )
        else:
            return TranscriptsFromGenes200ResponseInnerTranscript(
                id = '',
                transcript_type = '',
                chr = '',
                start = 1.337,
                end = 1.337,
                strand = '',
                name = '',
                gene_name = '',
                source = '',
                version = '',
                source_url = '',
        )
        """

    def testTranscriptsFromGenes200ResponseInnerTranscript(self):
        """Test TranscriptsFromGenes200ResponseInnerTranscript"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
