# coding: utf-8

"""
    IGVF Catalog

    IGVF Catalog OpenAPI compliant REST API built using tRPC with Express.  Our database uses 0-based, half-open coordinates for genomic coordinates in the GRCh38 (human) and GRCm39 (mouse) reference genomes.  Data is licensed under the <a href=https://creativecommons.org/licenses/by/4.0/ target=\"_blank\">Creative Commons license</a> and the software is licensed under the <a href=https://spdx.org/licenses/MIT.html target=\"_blank\">MIT license</a>.

    The version of the OpenAPI document: 1.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from igvf_catalog_client.models.diseases_from_genes_gene import DiseasesFromGenesGene

class TestDiseasesFromGenesGene(unittest.TestCase):
    """DiseasesFromGenesGene unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DiseasesFromGenesGene:
        """Test DiseasesFromGenesGene
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DiseasesFromGenesGene`
        """
        model = DiseasesFromGenesGene()
        if include_optional:
            return DiseasesFromGenesGene(
                id = '',
                chr = '',
                start = 1.337,
                end = 1.337,
                gene_type = '',
                name = '',
                strand = '',
                hgnc = '',
                entrez = '',
                collections = [
                    ''
                    ],
                study_sets = [
                    ''
                    ],
                source = '',
                version = '',
                source_url = '',
                synonyms = [
                    ''
                    ]
            )
        else:
            return DiseasesFromGenesGene(
                id = '',
                chr = '',
                start = 1.337,
                end = 1.337,
                gene_type = '',
                name = '',
                source = '',
                version = '',
                source_url = '',
        )
        """

    def testDiseasesFromGenesGene(self):
        """Test DiseasesFromGenesGene"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
