# coding: utf-8

"""
    IGVF Catalog

    IGVF Catalog OpenAPI compliant REST API built using tRPC with Express.  Our database uses 0-based, half-open coordinates for genomic coordinates in the GRCh38 (human) and GRCm39 (mouse) reference genomes.  Data is licensed under the <a href=https://creativecommons.org/licenses/by/4.0/ target=\"_blank\">Creative Commons license</a> and the software is licensed under the <a href=https://spdx.org/licenses/MIT.html target=\"_blank\">MIT license</a>.

    The version of the OpenAPI document: 1.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from igvf_catalog_client.models.enhancer_gene_predictions200_response_inner_elements import EnhancerGenePredictions200ResponseInnerElements

class TestEnhancerGenePredictions200ResponseInnerElements(unittest.TestCase):
    """EnhancerGenePredictions200ResponseInnerElements unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EnhancerGenePredictions200ResponseInnerElements:
        """Test EnhancerGenePredictions200ResponseInnerElements
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EnhancerGenePredictions200ResponseInnerElements`
        """
        model = EnhancerGenePredictions200ResponseInnerElements()
        if include_optional:
            return EnhancerGenePredictions200ResponseInnerElements(
                id = '',
                cell_type = '',
                score = 1.337,
                model = '',
                dataset = '',
                element_type = '',
                element_chr = '',
                element_start = 1.337,
                element_end = 1.337,
                name = '',
                method = '',
                var_class = '',
                files_filesets = ''
            )
        else:
            return EnhancerGenePredictions200ResponseInnerElements(
                id = '',
                name = '',
        )
        """

    def testEnhancerGenePredictions200ResponseInnerElements(self):
        """Test EnhancerGenePredictions200ResponseInnerElements"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
