# coding: utf-8

"""
    IGVF Catalog

    IGVF Catalog OpenAPI compliant REST API built using tRPC with Express.  Our database uses 0-based, half-open coordinates for genomic coordinates in the GRCh38 (human) and GRCm39 (mouse) reference genomes.  Data is licensed under the <a href=https://creativecommons.org/licenses/by/4.0/ target=\"_blank\">Creative Commons license</a> and the software is licensed under the <a href=https://spdx.org/licenses/MIT.html target=\"_blank\">MIT license</a>.

    The version of the OpenAPI document: 1.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from setuptools import setup, find_packages  # noqa: H301

# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools
NAME = "igvf-catalog-client"
VERSION = "1.2.0"
PYTHON_REQUIRES = ">= 3.9"
REQUIRES = [
    "urllib3 >= 2.1.0, < 3.0.0",
    "python-dateutil >= 2.8.2",
    "pydantic >= 2",
    "typing-extensions >= 4.7.1",
]

setup(
    name=NAME,
    version=VERSION,
    description="IGVF Catalog",
    author="OpenAPI Generator community",
    author_email="team@openapitools.org",
    url="",
    keywords=["OpenAPI", "OpenAPI-Generator", "IGVF Catalog"],
    install_requires=REQUIRES,
    packages=find_packages(exclude=["test", "tests"]),
    include_package_data=True,
    license="MIT",
    long_description_content_type='text/markdown',
    long_description="""\
    IGVF Catalog OpenAPI compliant REST API built using tRPC with Express.  Our database uses 0-based, half-open coordinates for genomic coordinates in the GRCh38 (human) and GRCm39 (mouse) reference genomes.  Data is licensed under the &lt;a href&#x3D;https://creativecommons.org/licenses/by/4.0/ target&#x3D;\&quot;_blank\&quot;&gt;Creative Commons license&lt;/a&gt; and the software is licensed under the &lt;a href&#x3D;https://spdx.org/licenses/MIT.html target&#x3D;\&quot;_blank\&quot;&gt;MIT license&lt;/a&gt;.
    """,  # noqa: E501
    package_data={"igvf_catalog_client": ["py.typed"]},
)