# coding: utf-8

"""
    IGVF Catalog

    IGVF Catalog OpenAPI compliant REST API built using tRPC with Express.  Our database uses 0-based, half-open coordinates for genomic coordinates in the GRCh38 (human) and GRCm39 (mouse) reference genomes.  Data is licensed under the <a href=https://creativecommons.org/licenses/by/4.0/ target=\"_blank\">Creative Commons license</a> and the software is licensed under the <a href=https://spdx.org/licenses/MIT.html target=\"_blank\">MIT license</a>.

    The version of the OpenAPI document: 1.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from igvf_catalog_client.models.coding_variant import CodingVariant
from igvf_catalog_client.models.phenotype_ref import PhenotypeRef
from igvf_catalog_client.models.variant_basic import VariantBasic
from typing import Optional, Set
from typing_extensions import Self

class CodingVariantsFromPhenotypes(BaseModel):
    """
    CodingVariantsFromPhenotypes
    """ # noqa: E501
    coding_variant: Optional[CodingVariant] = None
    phenotype: Optional[PhenotypeRef] = None
    score: Optional[Union[StrictFloat, StrictInt]]
    method: Optional[StrictStr] = None
    var_class: Optional[StrictStr] = Field(default=None, alias="class")
    label: Optional[StrictStr] = None
    files_filesets: Optional[StrictStr] = None
    source: StrictStr
    source_url: StrictStr
    variant: Optional[VariantBasic] = None
    __properties: ClassVar[List[str]] = ["coding_variant", "phenotype", "score", "method", "class", "label", "files_filesets", "source", "source_url", "variant"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CodingVariantsFromPhenotypes from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of coding_variant
        if self.coding_variant:
            _dict['coding_variant'] = self.coding_variant.to_dict()
        # override the default output from pydantic by calling `to_dict()` of phenotype
        if self.phenotype:
            _dict['phenotype'] = self.phenotype.to_dict()
        # override the default output from pydantic by calling `to_dict()` of variant
        if self.variant:
            _dict['variant'] = self.variant.to_dict()
        # set to None if coding_variant (nullable) is None
        # and model_fields_set contains the field
        if self.coding_variant is None and "coding_variant" in self.model_fields_set:
            _dict['coding_variant'] = None

        # set to None if phenotype (nullable) is None
        # and model_fields_set contains the field
        if self.phenotype is None and "phenotype" in self.model_fields_set:
            _dict['phenotype'] = None

        # set to None if score (nullable) is None
        # and model_fields_set contains the field
        if self.score is None and "score" in self.model_fields_set:
            _dict['score'] = None

        # set to None if method (nullable) is None
        # and model_fields_set contains the field
        if self.method is None and "method" in self.model_fields_set:
            _dict['method'] = None

        # set to None if var_class (nullable) is None
        # and model_fields_set contains the field
        if self.var_class is None and "var_class" in self.model_fields_set:
            _dict['class'] = None

        # set to None if label (nullable) is None
        # and model_fields_set contains the field
        if self.label is None and "label" in self.model_fields_set:
            _dict['label'] = None

        # set to None if files_filesets (nullable) is None
        # and model_fields_set contains the field
        if self.files_filesets is None and "files_filesets" in self.model_fields_set:
            _dict['files_filesets'] = None

        # set to None if variant (nullable) is None
        # and model_fields_set contains the field
        if self.variant is None and "variant" in self.model_fields_set:
            _dict['variant'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CodingVariantsFromPhenotypes from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "coding_variant": CodingVariant.from_dict(obj["coding_variant"]) if obj.get("coding_variant") is not None else None,
            "phenotype": PhenotypeRef.from_dict(obj["phenotype"]) if obj.get("phenotype") is not None else None,
            "score": obj.get("score"),
            "method": obj.get("method"),
            "class": obj.get("class"),
            "label": obj.get("label"),
            "files_filesets": obj.get("files_filesets"),
            "source": obj.get("source"),
            "source_url": obj.get("source_url"),
            "variant": VariantBasic.from_dict(obj["variant"]) if obj.get("variant") is not None else None
        })
        return _obj


