# coding: utf-8

"""
    IGVF Catalog

    IGVF Catalog OpenAPI compliant REST API built using tRPC with Express.  Our database uses 0-based, half-open coordinates for genomic coordinates in the GRCh38 (human) and GRCm39 (mouse) reference genomes.  Data is licensed under the <a href=https://creativecommons.org/licenses/by/4.0/ target=\"_blank\">Creative Commons license</a> and the software is licensed under the <a href=https://spdx.org/licenses/MIT.html target=\"_blank\">MIT license</a>.

    The version of the OpenAPI document: 1.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class CodingVariantsSummary(BaseModel):
    """
    CodingVariantsSummary
    """ # noqa: E501
    variant_id: Optional[StrictStr] = None
    hgvsp: Optional[StrictStr] = None
    gene_name: Optional[StrictStr] = None
    transcript_id: Optional[StrictStr] = None
    data_type: StrictStr = Field(alias="dataType")
    score: Optional[Union[StrictFloat, StrictInt]]
    portal_link: Optional[StrictStr] = Field(alias="portalLink")
    __properties: ClassVar[List[str]] = ["variant_id", "hgvsp", "gene_name", "transcript_id", "dataType", "score", "portalLink"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CodingVariantsSummary from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if variant_id (nullable) is None
        # and model_fields_set contains the field
        if self.variant_id is None and "variant_id" in self.model_fields_set:
            _dict['variant_id'] = None

        # set to None if hgvsp (nullable) is None
        # and model_fields_set contains the field
        if self.hgvsp is None and "hgvsp" in self.model_fields_set:
            _dict['hgvsp'] = None

        # set to None if gene_name (nullable) is None
        # and model_fields_set contains the field
        if self.gene_name is None and "gene_name" in self.model_fields_set:
            _dict['gene_name'] = None

        # set to None if transcript_id (nullable) is None
        # and model_fields_set contains the field
        if self.transcript_id is None and "transcript_id" in self.model_fields_set:
            _dict['transcript_id'] = None

        # set to None if score (nullable) is None
        # and model_fields_set contains the field
        if self.score is None and "score" in self.model_fields_set:
            _dict['score'] = None

        # set to None if portal_link (nullable) is None
        # and model_fields_set contains the field
        if self.portal_link is None and "portal_link" in self.model_fields_set:
            _dict['portalLink'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CodingVariantsSummary from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "variant_id": obj.get("variant_id"),
            "hgvsp": obj.get("hgvsp"),
            "gene_name": obj.get("gene_name"),
            "transcript_id": obj.get("transcript_id"),
            "dataType": obj.get("dataType"),
            "score": obj.get("score"),
            "portalLink": obj.get("portalLink")
        })
        return _obj


