# coding: utf-8

"""
    IGVF Catalog

    IGVF Catalog OpenAPI compliant REST API built using tRPC with Express.  Our database uses 0-based, half-open coordinates for genomic coordinates in the GRCh38 (human) and GRCm39 (mouse) reference genomes.  Data is licensed under the <a href=https://creativecommons.org/licenses/by/4.0/ target=\"_blank\">Creative Commons license</a> and the software is licensed under the <a href=https://spdx.org/licenses/MIT.html target=\"_blank\">MIT license</a>.

    The version of the OpenAPI document: 1.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict
from typing import Any, ClassVar, Dict, List
from igvf_catalog_client.models.coding_variants_from_genes200_response_inner_variants_inner_scores_inner import CodingVariantsFromGenes200ResponseInnerVariantsInnerScoresInner
from igvf_catalog_client.models.proteins_from_variants200_response_inner_sequence_variant_any_of import ProteinsFromVariants200ResponseInnerSequenceVariantAnyOf
from typing import Optional, Set
from typing_extensions import Self

class CodingVariantsFromGenes200ResponseInnerVariantsInner(BaseModel):
    """
    CodingVariantsFromGenes200ResponseInnerVariantsInner
    """ # noqa: E501
    variant: ProteinsFromVariants200ResponseInnerSequenceVariantAnyOf
    scores: List[CodingVariantsFromGenes200ResponseInnerVariantsInnerScoresInner]
    __properties: ClassVar[List[str]] = ["variant", "scores"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CodingVariantsFromGenes200ResponseInnerVariantsInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of variant
        if self.variant:
            _dict['variant'] = self.variant.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in scores (list)
        _items = []
        if self.scores:
            for _item_scores in self.scores:
                if _item_scores:
                    _items.append(_item_scores.to_dict())
            _dict['scores'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CodingVariantsFromGenes200ResponseInnerVariantsInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "variant": ProteinsFromVariants200ResponseInnerSequenceVariantAnyOf.from_dict(obj["variant"]) if obj.get("variant") is not None else None,
            "scores": [CodingVariantsFromGenes200ResponseInnerVariantsInnerScoresInner.from_dict(_item) for _item in obj["scores"]] if obj.get("scores") is not None else None
        })
        return _obj


