# coding: utf-8

"""
    IGVF Catalog

    IGVF Catalog OpenAPI compliant REST API built using tRPC with Express.  Our database uses 0-based, half-open coordinates for genomic coordinates in the GRCh38 (human) and GRCm39 (mouse) reference genomes.  Data is licensed under the <a href=https://creativecommons.org/licenses/by/4.0/ target=\"_blank\">Creative Commons license</a> and the software is licensed under the <a href=https://spdx.org/licenses/MIT.html target=\"_blank\">MIT license</a>.

    The version of the OpenAPI document: 1.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from igvf_catalog_client.models.complex_complex_assembly import ComplexComplexAssembly
from typing import Optional, Set
from typing_extensions import Self

class Complex(BaseModel):
    """
    Complex
    """ # noqa: E501
    id: StrictStr = Field(alias="_id")
    name: StrictStr
    alias: Optional[List[StrictStr]] = None
    molecules: Optional[List[StrictStr]] = None
    evidence_code: Optional[StrictStr] = None
    experimental_evidence: Optional[StrictStr] = None
    description: Optional[StrictStr] = None
    complex_assembly: Optional[ComplexComplexAssembly] = None
    complex_source: Optional[StrictStr] = None
    reactome_xref: Optional[List[StrictStr]] = None
    var_class: Optional[StrictStr] = Field(default=None, alias="class")
    method: Optional[StrictStr]
    label: Optional[StrictStr]
    files_filesets: Optional[StrictStr] = None
    source: StrictStr
    source_url: StrictStr
    __properties: ClassVar[List[str]] = ["_id", "name", "alias", "molecules", "evidence_code", "experimental_evidence", "description", "complex_assembly", "complex_source", "reactome_xref", "class", "method", "label", "files_filesets", "source", "source_url"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Complex from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of complex_assembly
        if self.complex_assembly:
            _dict['complex_assembly'] = self.complex_assembly.to_dict()
        # set to None if alias (nullable) is None
        # and model_fields_set contains the field
        if self.alias is None and "alias" in self.model_fields_set:
            _dict['alias'] = None

        # set to None if molecules (nullable) is None
        # and model_fields_set contains the field
        if self.molecules is None and "molecules" in self.model_fields_set:
            _dict['molecules'] = None

        # set to None if evidence_code (nullable) is None
        # and model_fields_set contains the field
        if self.evidence_code is None and "evidence_code" in self.model_fields_set:
            _dict['evidence_code'] = None

        # set to None if experimental_evidence (nullable) is None
        # and model_fields_set contains the field
        if self.experimental_evidence is None and "experimental_evidence" in self.model_fields_set:
            _dict['experimental_evidence'] = None

        # set to None if description (nullable) is None
        # and model_fields_set contains the field
        if self.description is None and "description" in self.model_fields_set:
            _dict['description'] = None

        # set to None if complex_assembly (nullable) is None
        # and model_fields_set contains the field
        if self.complex_assembly is None and "complex_assembly" in self.model_fields_set:
            _dict['complex_assembly'] = None

        # set to None if complex_source (nullable) is None
        # and model_fields_set contains the field
        if self.complex_source is None and "complex_source" in self.model_fields_set:
            _dict['complex_source'] = None

        # set to None if reactome_xref (nullable) is None
        # and model_fields_set contains the field
        if self.reactome_xref is None and "reactome_xref" in self.model_fields_set:
            _dict['reactome_xref'] = None

        # set to None if var_class (nullable) is None
        # and model_fields_set contains the field
        if self.var_class is None and "var_class" in self.model_fields_set:
            _dict['class'] = None

        # set to None if method (nullable) is None
        # and model_fields_set contains the field
        if self.method is None and "method" in self.model_fields_set:
            _dict['method'] = None

        # set to None if label (nullable) is None
        # and model_fields_set contains the field
        if self.label is None and "label" in self.model_fields_set:
            _dict['label'] = None

        # set to None if files_filesets (nullable) is None
        # and model_fields_set contains the field
        if self.files_filesets is None and "files_filesets" in self.model_fields_set:
            _dict['files_filesets'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Complex from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "_id": obj.get("_id"),
            "name": obj.get("name"),
            "alias": obj.get("alias"),
            "molecules": obj.get("molecules"),
            "evidence_code": obj.get("evidence_code"),
            "experimental_evidence": obj.get("experimental_evidence"),
            "description": obj.get("description"),
            "complex_assembly": ComplexComplexAssembly.from_dict(obj["complex_assembly"]) if obj.get("complex_assembly") is not None else None,
            "complex_source": obj.get("complex_source"),
            "reactome_xref": obj.get("reactome_xref"),
            "class": obj.get("class"),
            "method": obj.get("method"),
            "label": obj.get("label"),
            "files_filesets": obj.get("files_filesets"),
            "source": obj.get("source"),
            "source_url": obj.get("source_url")
        })
        return _obj


