# coding: utf-8

"""
    IGVF Catalog

    IGVF Catalog OpenAPI compliant REST API built using tRPC with Express.  Our database uses 0-based, half-open coordinates for genomic coordinates in the GRCh38 (human) and GRCm39 (mouse) reference genomes.  Data is licensed under the <a href=https://creativecommons.org/licenses/by/4.0/ target=\"_blank\">Creative Commons license</a> and the software is licensed under the <a href=https://spdx.org/licenses/MIT.html target=\"_blank\">MIT license</a>.

    The version of the OpenAPI document: 1.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from igvf_catalog_client.models.disease_from_variants200_response_inner_disease import DiseaseFromVariants200ResponseInnerDisease
from igvf_catalog_client.models.diseases_from_genes200_response_inner_variants_inner import DiseasesFromGenes200ResponseInnerVariantsInner
from igvf_catalog_client.models.proteins_from_genes200_response_inner_gene import ProteinsFromGenes200ResponseInnerGene
from typing import Optional, Set
from typing_extensions import Self

class DiseasesFromGenes200ResponseInner(BaseModel):
    """
    DiseasesFromGenes200ResponseInner
    """ # noqa: E501
    pmids: Optional[List[StrictStr]] = None
    term_name: Optional[StrictStr] = None
    gene_symbol: Optional[StrictStr] = None
    association_type: Optional[StrictStr] = None
    association_status: Optional[StrictStr] = None
    sgc_id: Optional[StrictStr] = None
    hgnc: Optional[StrictStr] = None
    classification: Optional[StrictStr] = None
    moi_id: Optional[StrictStr] = None
    moi_name: Optional[StrictStr] = None
    submitter: Optional[StrictStr] = None
    var_class: Optional[StrictStr] = Field(default=None, alias="class")
    method: Optional[StrictStr] = None
    label: Optional[StrictStr] = None
    files_filesets: Optional[StrictStr] = None
    source: Optional[StrictStr] = None
    source_url: Optional[StrictStr] = None
    gene: Optional[ProteinsFromGenes200ResponseInnerGene] = None
    disease: Optional[DiseaseFromVariants200ResponseInnerDisease] = None
    inheritance_mode: Optional[StrictStr] = None
    variants: Optional[List[DiseasesFromGenes200ResponseInnerVariantsInner]] = None
    name: StrictStr
    __properties: ClassVar[List[str]] = ["pmids", "term_name", "gene_symbol", "association_type", "association_status", "sgc_id", "hgnc", "classification", "moi_id", "moi_name", "submitter", "class", "method", "label", "files_filesets", "source", "source_url", "gene", "disease", "inheritance_mode", "variants", "name"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DiseasesFromGenes200ResponseInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of gene
        if self.gene:
            _dict['gene'] = self.gene.to_dict()
        # override the default output from pydantic by calling `to_dict()` of disease
        if self.disease:
            _dict['disease'] = self.disease.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in variants (list)
        _items = []
        if self.variants:
            for _item_variants in self.variants:
                if _item_variants:
                    _items.append(_item_variants.to_dict())
            _dict['variants'] = _items
        # set to None if pmids (nullable) is None
        # and model_fields_set contains the field
        if self.pmids is None and "pmids" in self.model_fields_set:
            _dict['pmids'] = None

        # set to None if association_type (nullable) is None
        # and model_fields_set contains the field
        if self.association_type is None and "association_type" in self.model_fields_set:
            _dict['association_type'] = None

        # set to None if association_status (nullable) is None
        # and model_fields_set contains the field
        if self.association_status is None and "association_status" in self.model_fields_set:
            _dict['association_status'] = None

        # set to None if sgc_id (nullable) is None
        # and model_fields_set contains the field
        if self.sgc_id is None and "sgc_id" in self.model_fields_set:
            _dict['sgc_id'] = None

        # set to None if hgnc (nullable) is None
        # and model_fields_set contains the field
        if self.hgnc is None and "hgnc" in self.model_fields_set:
            _dict['hgnc'] = None

        # set to None if classification (nullable) is None
        # and model_fields_set contains the field
        if self.classification is None and "classification" in self.model_fields_set:
            _dict['classification'] = None

        # set to None if moi_id (nullable) is None
        # and model_fields_set contains the field
        if self.moi_id is None and "moi_id" in self.model_fields_set:
            _dict['moi_id'] = None

        # set to None if moi_name (nullable) is None
        # and model_fields_set contains the field
        if self.moi_name is None and "moi_name" in self.model_fields_set:
            _dict['moi_name'] = None

        # set to None if submitter (nullable) is None
        # and model_fields_set contains the field
        if self.submitter is None and "submitter" in self.model_fields_set:
            _dict['submitter'] = None

        # set to None if var_class (nullable) is None
        # and model_fields_set contains the field
        if self.var_class is None and "var_class" in self.model_fields_set:
            _dict['class'] = None

        # set to None if method (nullable) is None
        # and model_fields_set contains the field
        if self.method is None and "method" in self.model_fields_set:
            _dict['method'] = None

        # set to None if label (nullable) is None
        # and model_fields_set contains the field
        if self.label is None and "label" in self.model_fields_set:
            _dict['label'] = None

        # set to None if files_filesets (nullable) is None
        # and model_fields_set contains the field
        if self.files_filesets is None and "files_filesets" in self.model_fields_set:
            _dict['files_filesets'] = None

        # set to None if inheritance_mode (nullable) is None
        # and model_fields_set contains the field
        if self.inheritance_mode is None and "inheritance_mode" in self.model_fields_set:
            _dict['inheritance_mode'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DiseasesFromGenes200ResponseInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "pmids": obj.get("pmids"),
            "term_name": obj.get("term_name"),
            "gene_symbol": obj.get("gene_symbol"),
            "association_type": obj.get("association_type"),
            "association_status": obj.get("association_status"),
            "sgc_id": obj.get("sgc_id"),
            "hgnc": obj.get("hgnc"),
            "classification": obj.get("classification"),
            "moi_id": obj.get("moi_id"),
            "moi_name": obj.get("moi_name"),
            "submitter": obj.get("submitter"),
            "class": obj.get("class"),
            "method": obj.get("method"),
            "label": obj.get("label"),
            "files_filesets": obj.get("files_filesets"),
            "source": obj.get("source"),
            "source_url": obj.get("source_url"),
            "gene": ProteinsFromGenes200ResponseInnerGene.from_dict(obj["gene"]) if obj.get("gene") is not None else None,
            "disease": DiseaseFromVariants200ResponseInnerDisease.from_dict(obj["disease"]) if obj.get("disease") is not None else None,
            "inheritance_mode": obj.get("inheritance_mode"),
            "variants": [DiseasesFromGenes200ResponseInnerVariantsInner.from_dict(_item) for _item in obj["variants"]] if obj.get("variants") is not None else None,
            "name": obj.get("name")
        })
        return _obj


