# coding: utf-8

"""
    IGVF Catalog

    IGVF Catalog OpenAPI compliant REST API built using tRPC with Express.  Our database uses 0-based, half-open coordinates for genomic coordinates in the GRCh38 (human) and GRCm39 (mouse) reference genomes.  Data is licensed under the <a href=https://creativecommons.org/licenses/by/4.0/ target=\"_blank\">Creative Commons license</a> and the software is licensed under the <a href=https://spdx.org/licenses/MIT.html target=\"_blank\">MIT license</a>.

    The version of the OpenAPI document: 1.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from igvf_catalog_client.models.biosamples_from_genomic_elements_biosample import BiosamplesFromGenomicElementsBiosample
from igvf_catalog_client.models.disease_from_variants_sequence_variant import DiseaseFromVariantsSequenceVariant
from typing import Optional, Set
from typing_extensions import Self

class DiseaseFromVariants(BaseModel):
    """
    DiseaseFromVariants
    """ # noqa: E501
    sequence_variant: Optional[DiseaseFromVariantsSequenceVariant] = None
    disease: Optional[BiosamplesFromGenomicElementsBiosample] = None
    gene_id: Optional[StrictStr] = None
    gene_name: Optional[StrictStr] = None
    assertion: Optional[StrictStr] = None
    pmids: Optional[List[StrictStr]] = None
    var_class: Optional[StrictStr] = Field(default=None, alias="class")
    method: Optional[StrictStr] = None
    label: Optional[StrictStr] = None
    files_filesets: Optional[StrictStr] = None
    source: Optional[StrictStr] = None
    source_url: Optional[StrictStr] = None
    name: StrictStr
    __properties: ClassVar[List[str]] = ["sequence_variant", "disease", "gene_id", "gene_name", "assertion", "pmids", "class", "method", "label", "files_filesets", "source", "source_url", "name"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DiseaseFromVariants from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of sequence_variant
        if self.sequence_variant:
            _dict['sequence_variant'] = self.sequence_variant.to_dict()
        # override the default output from pydantic by calling `to_dict()` of disease
        if self.disease:
            _dict['disease'] = self.disease.to_dict()
        # set to None if var_class (nullable) is None
        # and model_fields_set contains the field
        if self.var_class is None and "var_class" in self.model_fields_set:
            _dict['class'] = None

        # set to None if method (nullable) is None
        # and model_fields_set contains the field
        if self.method is None and "method" in self.model_fields_set:
            _dict['method'] = None

        # set to None if label (nullable) is None
        # and model_fields_set contains the field
        if self.label is None and "label" in self.model_fields_set:
            _dict['label'] = None

        # set to None if files_filesets (nullable) is None
        # and model_fields_set contains the field
        if self.files_filesets is None and "files_filesets" in self.model_fields_set:
            _dict['files_filesets'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DiseaseFromVariants from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "sequence_variant": DiseaseFromVariantsSequenceVariant.from_dict(obj["sequence_variant"]) if obj.get("sequence_variant") is not None else None,
            "disease": BiosamplesFromGenomicElementsBiosample.from_dict(obj["disease"]) if obj.get("disease") is not None else None,
            "gene_id": obj.get("gene_id"),
            "gene_name": obj.get("gene_name"),
            "assertion": obj.get("assertion"),
            "pmids": obj.get("pmids"),
            "class": obj.get("class"),
            "method": obj.get("method"),
            "label": obj.get("label"),
            "files_filesets": obj.get("files_filesets"),
            "source": obj.get("source"),
            "source_url": obj.get("source_url"),
            "name": obj.get("name")
        })
        return _obj


