# coding: utf-8

"""
    IGVF Catalog

    IGVF Catalog OpenAPI compliant REST API built using tRPC with Express.  Our database uses 0-based, half-open coordinates for genomic coordinates in the GRCh38 (human) and GRCm39 (mouse) reference genomes.  Data is licensed under the <a href=https://creativecommons.org/licenses/by/4.0/ target=\"_blank\">Creative Commons license</a> and the software is licensed under the <a href=https://spdx.org/licenses/MIT.html target=\"_blank\">MIT license</a>.

    The version of the OpenAPI document: 1.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from igvf_catalog_client.models.drugs_from_variants200_response_inner_drug import DrugsFromVariants200ResponseInnerDrug
from igvf_catalog_client.models.drugs_from_variants200_response_inner_study_parameters_inner import DrugsFromVariants200ResponseInnerStudyParametersInner
from typing import Optional, Set
from typing_extensions import Self

class DrugsFromVariants200ResponseInner(BaseModel):
    """
    DrugsFromVariants200ResponseInner
    """ # noqa: E501
    drug: Optional[DrugsFromVariants200ResponseInnerDrug] = None
    var_from: StrictStr = Field(alias="_from")
    gene_symbol: Optional[List[StrictStr]] = None
    pmid: Optional[StrictStr] = None
    study_parameters: Optional[List[DrugsFromVariants200ResponseInnerStudyParametersInner]] = None
    phenotype_categories: Optional[List[StrictStr]] = None
    source: StrictStr
    source_url: StrictStr
    name: StrictStr
    var_class: Optional[StrictStr] = Field(default=None, alias="class")
    method: Optional[StrictStr] = None
    files_filesets: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["drug", "_from", "gene_symbol", "pmid", "study_parameters", "phenotype_categories", "source", "source_url", "name", "class", "method", "files_filesets"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DrugsFromVariants200ResponseInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of drug
        if self.drug:
            _dict['drug'] = self.drug.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in study_parameters (list)
        _items = []
        if self.study_parameters:
            for _item_study_parameters in self.study_parameters:
                if _item_study_parameters:
                    _items.append(_item_study_parameters.to_dict())
            _dict['study_parameters'] = _items
        # set to None if var_class (nullable) is None
        # and model_fields_set contains the field
        if self.var_class is None and "var_class" in self.model_fields_set:
            _dict['class'] = None

        # set to None if method (nullable) is None
        # and model_fields_set contains the field
        if self.method is None and "method" in self.model_fields_set:
            _dict['method'] = None

        # set to None if files_filesets (nullable) is None
        # and model_fields_set contains the field
        if self.files_filesets is None and "files_filesets" in self.model_fields_set:
            _dict['files_filesets'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DrugsFromVariants200ResponseInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "drug": DrugsFromVariants200ResponseInnerDrug.from_dict(obj["drug"]) if obj.get("drug") is not None else None,
            "_from": obj.get("_from"),
            "gene_symbol": obj.get("gene_symbol"),
            "pmid": obj.get("pmid"),
            "study_parameters": [DrugsFromVariants200ResponseInnerStudyParametersInner.from_dict(_item) for _item in obj["study_parameters"]] if obj.get("study_parameters") is not None else None,
            "phenotype_categories": obj.get("phenotype_categories"),
            "source": obj.get("source"),
            "source_url": obj.get("source_url"),
            "name": obj.get("name"),
            "class": obj.get("class"),
            "method": obj.get("method"),
            "files_filesets": obj.get("files_filesets")
        })
        return _obj


