# coding: utf-8

"""
    IGVF Catalog

    IGVF Catalog OpenAPI compliant REST API built using tRPC with Express.  Our database uses 0-based, half-open coordinates for genomic coordinates in the GRCh38 (human) and GRCm39 (mouse) reference genomes.  Data is licensed under the <a href=https://creativecommons.org/licenses/by/4.0/ target=\"_blank\">Creative Commons license</a> and the software is licensed under the <a href=https://spdx.org/licenses/MIT.html target=\"_blank\">MIT license</a>.

    The version of the OpenAPI document: 1.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class Elements(BaseModel):
    """
    Elements
    """ # noqa: E501
    id: StrictStr
    cell_type: Optional[StrictStr] = None
    score: Optional[Union[StrictFloat, StrictInt]] = None
    model: Optional[StrictStr] = None
    dataset: Optional[StrictStr] = None
    element_type: Optional[StrictStr] = None
    element_chr: Optional[StrictStr] = None
    element_start: Optional[Union[StrictFloat, StrictInt]] = None
    element_end: Optional[Union[StrictFloat, StrictInt]] = None
    name: StrictStr
    method: Optional[StrictStr] = None
    var_class: Optional[StrictStr] = Field(default=None, alias="class")
    files_filesets: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["id", "cell_type", "score", "model", "dataset", "element_type", "element_chr", "element_start", "element_end", "name", "method", "class", "files_filesets"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Elements from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if cell_type (nullable) is None
        # and model_fields_set contains the field
        if self.cell_type is None and "cell_type" in self.model_fields_set:
            _dict['cell_type'] = None

        # set to None if score (nullable) is None
        # and model_fields_set contains the field
        if self.score is None and "score" in self.model_fields_set:
            _dict['score'] = None

        # set to None if model (nullable) is None
        # and model_fields_set contains the field
        if self.model is None and "model" in self.model_fields_set:
            _dict['model'] = None

        # set to None if dataset (nullable) is None
        # and model_fields_set contains the field
        if self.dataset is None and "dataset" in self.model_fields_set:
            _dict['dataset'] = None

        # set to None if element_type (nullable) is None
        # and model_fields_set contains the field
        if self.element_type is None and "element_type" in self.model_fields_set:
            _dict['element_type'] = None

        # set to None if element_chr (nullable) is None
        # and model_fields_set contains the field
        if self.element_chr is None and "element_chr" in self.model_fields_set:
            _dict['element_chr'] = None

        # set to None if element_start (nullable) is None
        # and model_fields_set contains the field
        if self.element_start is None and "element_start" in self.model_fields_set:
            _dict['element_start'] = None

        # set to None if element_end (nullable) is None
        # and model_fields_set contains the field
        if self.element_end is None and "element_end" in self.model_fields_set:
            _dict['element_end'] = None

        # set to None if files_filesets (nullable) is None
        # and model_fields_set contains the field
        if self.files_filesets is None and "files_filesets" in self.model_fields_set:
            _dict['files_filesets'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Elements from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "cell_type": obj.get("cell_type"),
            "score": obj.get("score"),
            "model": obj.get("model"),
            "dataset": obj.get("dataset"),
            "element_type": obj.get("element_type"),
            "element_chr": obj.get("element_chr"),
            "element_start": obj.get("element_start"),
            "element_end": obj.get("element_end"),
            "name": obj.get("name"),
            "method": obj.get("method"),
            "class": obj.get("class"),
            "files_filesets": obj.get("files_filesets")
        })
        return _obj


