# coding: utf-8

"""
    IGVF Catalog

    IGVF Catalog OpenAPI compliant REST API built using tRPC with Express.  Our database uses 0-based, half-open coordinates for genomic coordinates in the GRCh38 (human) and GRCm39 (mouse) reference genomes.  Data is licensed under the <a href=https://creativecommons.org/licenses/by/4.0/ target=\"_blank\">Creative Commons license</a> and the software is licensed under the <a href=https://spdx.org/licenses/MIT.html target=\"_blank\">MIT license</a>.

    The version of the OpenAPI document: 1.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict
from typing import Any, ClassVar, Dict, List, Optional
from igvf_catalog_client.models.genes_proteins_from_variants200_response_inner_related_inner_gene_any_of import GenesProteinsFromVariants200ResponseInnerRelatedInnerGeneAnyOf
from igvf_catalog_client.models.genes_proteins_from_variants200_response_inner_related_inner_protein import GenesProteinsFromVariants200ResponseInnerRelatedInnerProtein
from igvf_catalog_client.models.genes_proteins_genes_proteins200_response_inner_related_inner import GenesProteinsGenesProteins200ResponseInnerRelatedInner
from typing import Optional, Set
from typing_extensions import Self

class GenesProteinsGenesProteins200ResponseInner(BaseModel):
    """
    GenesProteinsGenesProteins200ResponseInner
    """ # noqa: E501
    protein: Optional[GenesProteinsFromVariants200ResponseInnerRelatedInnerProtein] = None
    gene: Optional[GenesProteinsFromVariants200ResponseInnerRelatedInnerGeneAnyOf] = None
    related: Optional[List[GenesProteinsGenesProteins200ResponseInnerRelatedInner]] = None
    __properties: ClassVar[List[str]] = ["protein", "gene", "related"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GenesProteinsGenesProteins200ResponseInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of protein
        if self.protein:
            _dict['protein'] = self.protein.to_dict()
        # override the default output from pydantic by calling `to_dict()` of gene
        if self.gene:
            _dict['gene'] = self.gene.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in related (list)
        _items = []
        if self.related:
            for _item_related in self.related:
                if _item_related:
                    _items.append(_item_related.to_dict())
            _dict['related'] = _items
        # set to None if protein (nullable) is None
        # and model_fields_set contains the field
        if self.protein is None and "protein" in self.model_fields_set:
            _dict['protein'] = None

        # set to None if gene (nullable) is None
        # and model_fields_set contains the field
        if self.gene is None and "gene" in self.model_fields_set:
            _dict['gene'] = None

        # set to None if related (nullable) is None
        # and model_fields_set contains the field
        if self.related is None and "related" in self.model_fields_set:
            _dict['related'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GenesProteinsGenesProteins200ResponseInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "protein": GenesProteinsFromVariants200ResponseInnerRelatedInnerProtein.from_dict(obj["protein"]) if obj.get("protein") is not None else None,
            "gene": GenesProteinsFromVariants200ResponseInnerRelatedInnerGeneAnyOf.from_dict(obj["gene"]) if obj.get("gene") is not None else None,
            "related": [GenesProteinsGenesProteins200ResponseInnerRelatedInner.from_dict(_item) for _item in obj["related"]] if obj.get("related") is not None else None
        })
        return _obj


