# coding: utf-8

"""
    IGVF Catalog

    IGVF Catalog OpenAPI compliant REST API built using tRPC with Express.  Our database uses 0-based, half-open coordinates for genomic coordinates in the GRCh38 (human) and GRCm39 (mouse) reference genomes.  Data is licensed under the <a href=https://creativecommons.org/licenses/by/4.0/ target=\"_blank\">Creative Commons license</a> and the software is licensed under the <a href=https://spdx.org/licenses/MIT.html target=\"_blank\">MIT license</a>.

    The version of the OpenAPI document: 1.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class GenesStructure(BaseModel):
    """
    GenesStructure
    """ # noqa: E501
    id: StrictStr = Field(alias="_id")
    name: StrictStr
    chr: StrictStr
    start: Optional[Union[StrictFloat, StrictInt]]
    end: Optional[Union[StrictFloat, StrictInt]]
    strand: StrictStr
    type: StrictStr
    gene_id: StrictStr
    gene_name: StrictStr
    transcript_id: StrictStr
    transcript_name: StrictStr
    protein_id: Optional[StrictStr] = None
    exon_number: StrictStr
    exon_id: Optional[StrictStr]
    organism: StrictStr
    source: StrictStr
    version: StrictStr
    source_url: StrictStr
    __properties: ClassVar[List[str]] = ["_id", "name", "chr", "start", "end", "strand", "type", "gene_id", "gene_name", "transcript_id", "transcript_name", "protein_id", "exon_number", "exon_id", "organism", "source", "version", "source_url"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GenesStructure from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if start (nullable) is None
        # and model_fields_set contains the field
        if self.start is None and "start" in self.model_fields_set:
            _dict['start'] = None

        # set to None if end (nullable) is None
        # and model_fields_set contains the field
        if self.end is None and "end" in self.model_fields_set:
            _dict['end'] = None

        # set to None if protein_id (nullable) is None
        # and model_fields_set contains the field
        if self.protein_id is None and "protein_id" in self.model_fields_set:
            _dict['protein_id'] = None

        # set to None if exon_id (nullable) is None
        # and model_fields_set contains the field
        if self.exon_id is None and "exon_id" in self.model_fields_set:
            _dict['exon_id'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GenesStructure from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "_id": obj.get("_id"),
            "name": obj.get("name"),
            "chr": obj.get("chr"),
            "start": obj.get("start"),
            "end": obj.get("end"),
            "strand": obj.get("strand"),
            "type": obj.get("type"),
            "gene_id": obj.get("gene_id"),
            "gene_name": obj.get("gene_name"),
            "transcript_id": obj.get("transcript_id"),
            "transcript_name": obj.get("transcript_name"),
            "protein_id": obj.get("protein_id"),
            "exon_number": obj.get("exon_number"),
            "exon_id": obj.get("exon_id"),
            "organism": obj.get("organism"),
            "source": obj.get("source"),
            "version": obj.get("version"),
            "source_url": obj.get("source_url")
        })
        return _obj


