# coding: utf-8

"""
    IGVF Catalog

    IGVF Catalog OpenAPI compliant REST API built using tRPC with Express.  Our database uses 0-based, half-open coordinates for genomic coordinates in the GRCh38 (human) and GRCm39 (mouse) reference genomes.  Data is licensed under the <a href=https://creativecommons.org/licenses/by/4.0/ target=\"_blank\">Creative Commons license</a> and the software is licensed under the <a href=https://spdx.org/licenses/MIT.html target=\"_blank\">MIT license</a>.

    The version of the OpenAPI document: 1.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class GenesFromVariants200ResponseInnerStudyAnyOf(BaseModel):
    """
    GenesFromVariants200ResponseInnerStudyAnyOf
    """ # noqa: E501
    id: StrictStr = Field(alias="_id")
    name: StrictStr
    ancestry_initial: Optional[StrictStr]
    ancestry_replication: Optional[StrictStr]
    n_cases: Optional[StrictStr]
    n_initial: Optional[StrictStr]
    n_replication: Optional[StrictStr]
    pmid: Optional[StrictStr]
    pub_author: Optional[StrictStr]
    pub_date: Optional[StrictStr]
    pub_journal: Optional[StrictStr]
    pub_title: Optional[StrictStr]
    has_sumstats: Optional[StrictStr]
    num_assoc_loci: Optional[StrictStr]
    study_source: Optional[StrictStr]
    trait_reported: Optional[StrictStr]
    trait_efos: Optional[StrictStr]
    trait_category: Optional[StrictStr]
    source: Optional[StrictStr] = None
    study_type: Optional[StrictStr]
    version: Optional[StrictStr]
    files_filesets: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["_id", "name", "ancestry_initial", "ancestry_replication", "n_cases", "n_initial", "n_replication", "pmid", "pub_author", "pub_date", "pub_journal", "pub_title", "has_sumstats", "num_assoc_loci", "study_source", "trait_reported", "trait_efos", "trait_category", "source", "study_type", "version", "files_filesets"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GenesFromVariants200ResponseInnerStudyAnyOf from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if ancestry_initial (nullable) is None
        # and model_fields_set contains the field
        if self.ancestry_initial is None and "ancestry_initial" in self.model_fields_set:
            _dict['ancestry_initial'] = None

        # set to None if ancestry_replication (nullable) is None
        # and model_fields_set contains the field
        if self.ancestry_replication is None and "ancestry_replication" in self.model_fields_set:
            _dict['ancestry_replication'] = None

        # set to None if n_cases (nullable) is None
        # and model_fields_set contains the field
        if self.n_cases is None and "n_cases" in self.model_fields_set:
            _dict['n_cases'] = None

        # set to None if n_initial (nullable) is None
        # and model_fields_set contains the field
        if self.n_initial is None and "n_initial" in self.model_fields_set:
            _dict['n_initial'] = None

        # set to None if n_replication (nullable) is None
        # and model_fields_set contains the field
        if self.n_replication is None and "n_replication" in self.model_fields_set:
            _dict['n_replication'] = None

        # set to None if pmid (nullable) is None
        # and model_fields_set contains the field
        if self.pmid is None and "pmid" in self.model_fields_set:
            _dict['pmid'] = None

        # set to None if pub_author (nullable) is None
        # and model_fields_set contains the field
        if self.pub_author is None and "pub_author" in self.model_fields_set:
            _dict['pub_author'] = None

        # set to None if pub_date (nullable) is None
        # and model_fields_set contains the field
        if self.pub_date is None and "pub_date" in self.model_fields_set:
            _dict['pub_date'] = None

        # set to None if pub_journal (nullable) is None
        # and model_fields_set contains the field
        if self.pub_journal is None and "pub_journal" in self.model_fields_set:
            _dict['pub_journal'] = None

        # set to None if pub_title (nullable) is None
        # and model_fields_set contains the field
        if self.pub_title is None and "pub_title" in self.model_fields_set:
            _dict['pub_title'] = None

        # set to None if has_sumstats (nullable) is None
        # and model_fields_set contains the field
        if self.has_sumstats is None and "has_sumstats" in self.model_fields_set:
            _dict['has_sumstats'] = None

        # set to None if num_assoc_loci (nullable) is None
        # and model_fields_set contains the field
        if self.num_assoc_loci is None and "num_assoc_loci" in self.model_fields_set:
            _dict['num_assoc_loci'] = None

        # set to None if study_source (nullable) is None
        # and model_fields_set contains the field
        if self.study_source is None and "study_source" in self.model_fields_set:
            _dict['study_source'] = None

        # set to None if trait_reported (nullable) is None
        # and model_fields_set contains the field
        if self.trait_reported is None and "trait_reported" in self.model_fields_set:
            _dict['trait_reported'] = None

        # set to None if trait_efos (nullable) is None
        # and model_fields_set contains the field
        if self.trait_efos is None and "trait_efos" in self.model_fields_set:
            _dict['trait_efos'] = None

        # set to None if trait_category (nullable) is None
        # and model_fields_set contains the field
        if self.trait_category is None and "trait_category" in self.model_fields_set:
            _dict['trait_category'] = None

        # set to None if study_type (nullable) is None
        # and model_fields_set contains the field
        if self.study_type is None and "study_type" in self.model_fields_set:
            _dict['study_type'] = None

        # set to None if version (nullable) is None
        # and model_fields_set contains the field
        if self.version is None and "version" in self.model_fields_set:
            _dict['version'] = None

        # set to None if files_filesets (nullable) is None
        # and model_fields_set contains the field
        if self.files_filesets is None and "files_filesets" in self.model_fields_set:
            _dict['files_filesets'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GenesFromVariants200ResponseInnerStudyAnyOf from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "_id": obj.get("_id"),
            "name": obj.get("name"),
            "ancestry_initial": obj.get("ancestry_initial"),
            "ancestry_replication": obj.get("ancestry_replication"),
            "n_cases": obj.get("n_cases"),
            "n_initial": obj.get("n_initial"),
            "n_replication": obj.get("n_replication"),
            "pmid": obj.get("pmid"),
            "pub_author": obj.get("pub_author"),
            "pub_date": obj.get("pub_date"),
            "pub_journal": obj.get("pub_journal"),
            "pub_title": obj.get("pub_title"),
            "has_sumstats": obj.get("has_sumstats"),
            "num_assoc_loci": obj.get("num_assoc_loci"),
            "study_source": obj.get("study_source"),
            "trait_reported": obj.get("trait_reported"),
            "trait_efos": obj.get("trait_efos"),
            "trait_category": obj.get("trait_category"),
            "source": obj.get("source"),
            "study_type": obj.get("study_type"),
            "version": obj.get("version"),
            "files_filesets": obj.get("files_filesets")
        })
        return _obj


