# coding: utf-8

"""
    IGVF Catalog

    IGVF Catalog OpenAPI compliant REST API built using tRPC with Express.  Our database uses 0-based, half-open coordinates for genomic coordinates in the GRCh38 (human) and GRCm39 (mouse) reference genomes.  Data is licensed under the <a href=https://creativecommons.org/licenses/by/4.0/ target=\"_blank\">Creative Commons license</a> and the software is licensed under the <a href=https://spdx.org/licenses/MIT.html target=\"_blank\">MIT license</a>.

    The version of the OpenAPI document: 1.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from igvf_catalog_client.models.genes_from_genomic_elements_p_value import GenesFromGenomicElementsPValue
from igvf_catalog_client.models.genes_from_variants_gene import GenesFromVariantsGene
from igvf_catalog_client.models.genes_from_variants_sequence_variant import GenesFromVariantsSequenceVariant
from igvf_catalog_client.models.genes_from_variants_study import GenesFromVariantsStudy
from typing import Optional, Set
from typing_extensions import Self

class GenesFromVariants(BaseModel):
    """
    GenesFromVariants
    """ # noqa: E501
    gene: Optional[GenesFromVariantsGene]
    sequence_variant: Optional[GenesFromVariantsSequenceVariant]
    intron_chr: Optional[StrictStr] = None
    intron_start: Optional[StrictStr] = None
    intron_end: Optional[StrictStr] = None
    effect_size: Optional[Union[StrictFloat, StrictInt]] = None
    neg_log10_pvalue: Optional[GenesFromGenomicElementsPValue] = None
    neg_log10_pvalue_adj: Optional[Union[StrictFloat, StrictInt]] = None
    log2_fc: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="log2FC")
    posterior_inclusion_probability: Optional[Union[StrictFloat, StrictInt]] = None
    coefficient_stddev: Optional[Union[StrictFloat, StrictInt]] = None
    power: Optional[Union[StrictFloat, StrictInt]] = None
    significant: Optional[StrictBool] = None
    standard_error: Optional[Union[StrictFloat, StrictInt]] = None
    z_score: Optional[Union[StrictFloat, StrictInt]] = None
    credible_set_min_r2: Optional[Union[StrictFloat, StrictInt]] = None
    method: Optional[StrictStr] = None
    crispr_modality: Optional[StrictStr] = None
    source: StrictStr
    source_url: StrictStr
    label: StrictStr
    p_value: Optional[Union[StrictFloat, StrictInt]] = None
    chr: Optional[StrictStr] = None
    biological_context: StrictStr
    biosample_term: StrictStr
    study: Optional[GenesFromVariantsStudy] = None
    name: Optional[StrictStr] = None
    var_class: Optional[StrictStr] = Field(default=None, alias="class")
    files_filesets: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["gene", "sequence_variant", "intron_chr", "intron_start", "intron_end", "effect_size", "neg_log10_pvalue", "neg_log10_pvalue_adj", "log2FC", "posterior_inclusion_probability", "coefficient_stddev", "power", "significant", "standard_error", "z_score", "credible_set_min_r2", "method", "crispr_modality", "source", "source_url", "label", "p_value", "chr", "biological_context", "biosample_term", "study", "name", "class", "files_filesets"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GenesFromVariants from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of gene
        if self.gene:
            _dict['gene'] = self.gene.to_dict()
        # override the default output from pydantic by calling `to_dict()` of sequence_variant
        if self.sequence_variant:
            _dict['sequence_variant'] = self.sequence_variant.to_dict()
        # override the default output from pydantic by calling `to_dict()` of neg_log10_pvalue
        if self.neg_log10_pvalue:
            _dict['neg_log10_pvalue'] = self.neg_log10_pvalue.to_dict()
        # override the default output from pydantic by calling `to_dict()` of study
        if self.study:
            _dict['study'] = self.study.to_dict()
        # set to None if gene (nullable) is None
        # and model_fields_set contains the field
        if self.gene is None and "gene" in self.model_fields_set:
            _dict['gene'] = None

        # set to None if sequence_variant (nullable) is None
        # and model_fields_set contains the field
        if self.sequence_variant is None and "sequence_variant" in self.model_fields_set:
            _dict['sequence_variant'] = None

        # set to None if intron_chr (nullable) is None
        # and model_fields_set contains the field
        if self.intron_chr is None and "intron_chr" in self.model_fields_set:
            _dict['intron_chr'] = None

        # set to None if intron_start (nullable) is None
        # and model_fields_set contains the field
        if self.intron_start is None and "intron_start" in self.model_fields_set:
            _dict['intron_start'] = None

        # set to None if intron_end (nullable) is None
        # and model_fields_set contains the field
        if self.intron_end is None and "intron_end" in self.model_fields_set:
            _dict['intron_end'] = None

        # set to None if effect_size (nullable) is None
        # and model_fields_set contains the field
        if self.effect_size is None and "effect_size" in self.model_fields_set:
            _dict['effect_size'] = None

        # set to None if neg_log10_pvalue (nullable) is None
        # and model_fields_set contains the field
        if self.neg_log10_pvalue is None and "neg_log10_pvalue" in self.model_fields_set:
            _dict['neg_log10_pvalue'] = None

        # set to None if neg_log10_pvalue_adj (nullable) is None
        # and model_fields_set contains the field
        if self.neg_log10_pvalue_adj is None and "neg_log10_pvalue_adj" in self.model_fields_set:
            _dict['neg_log10_pvalue_adj'] = None

        # set to None if log2_fc (nullable) is None
        # and model_fields_set contains the field
        if self.log2_fc is None and "log2_fc" in self.model_fields_set:
            _dict['log2FC'] = None

        # set to None if posterior_inclusion_probability (nullable) is None
        # and model_fields_set contains the field
        if self.posterior_inclusion_probability is None and "posterior_inclusion_probability" in self.model_fields_set:
            _dict['posterior_inclusion_probability'] = None

        # set to None if coefficient_stddev (nullable) is None
        # and model_fields_set contains the field
        if self.coefficient_stddev is None and "coefficient_stddev" in self.model_fields_set:
            _dict['coefficient_stddev'] = None

        # set to None if power (nullable) is None
        # and model_fields_set contains the field
        if self.power is None and "power" in self.model_fields_set:
            _dict['power'] = None

        # set to None if significant (nullable) is None
        # and model_fields_set contains the field
        if self.significant is None and "significant" in self.model_fields_set:
            _dict['significant'] = None

        # set to None if standard_error (nullable) is None
        # and model_fields_set contains the field
        if self.standard_error is None and "standard_error" in self.model_fields_set:
            _dict['standard_error'] = None

        # set to None if z_score (nullable) is None
        # and model_fields_set contains the field
        if self.z_score is None and "z_score" in self.model_fields_set:
            _dict['z_score'] = None

        # set to None if credible_set_min_r2 (nullable) is None
        # and model_fields_set contains the field
        if self.credible_set_min_r2 is None and "credible_set_min_r2" in self.model_fields_set:
            _dict['credible_set_min_r2'] = None

        # set to None if method (nullable) is None
        # and model_fields_set contains the field
        if self.method is None and "method" in self.model_fields_set:
            _dict['method'] = None

        # set to None if crispr_modality (nullable) is None
        # and model_fields_set contains the field
        if self.crispr_modality is None and "crispr_modality" in self.model_fields_set:
            _dict['crispr_modality'] = None

        # set to None if p_value (nullable) is None
        # and model_fields_set contains the field
        if self.p_value is None and "p_value" in self.model_fields_set:
            _dict['p_value'] = None

        # set to None if chr (nullable) is None
        # and model_fields_set contains the field
        if self.chr is None and "chr" in self.model_fields_set:
            _dict['chr'] = None

        # set to None if study (nullable) is None
        # and model_fields_set contains the field
        if self.study is None and "study" in self.model_fields_set:
            _dict['study'] = None

        # set to None if name (nullable) is None
        # and model_fields_set contains the field
        if self.name is None and "name" in self.model_fields_set:
            _dict['name'] = None

        # set to None if var_class (nullable) is None
        # and model_fields_set contains the field
        if self.var_class is None and "var_class" in self.model_fields_set:
            _dict['class'] = None

        # set to None if files_filesets (nullable) is None
        # and model_fields_set contains the field
        if self.files_filesets is None and "files_filesets" in self.model_fields_set:
            _dict['files_filesets'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GenesFromVariants from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "gene": GenesFromVariantsGene.from_dict(obj["gene"]) if obj.get("gene") is not None else None,
            "sequence_variant": GenesFromVariantsSequenceVariant.from_dict(obj["sequence_variant"]) if obj.get("sequence_variant") is not None else None,
            "intron_chr": obj.get("intron_chr"),
            "intron_start": obj.get("intron_start"),
            "intron_end": obj.get("intron_end"),
            "effect_size": obj.get("effect_size"),
            "neg_log10_pvalue": GenesFromGenomicElementsPValue.from_dict(obj["neg_log10_pvalue"]) if obj.get("neg_log10_pvalue") is not None else None,
            "neg_log10_pvalue_adj": obj.get("neg_log10_pvalue_adj"),
            "log2FC": obj.get("log2FC"),
            "posterior_inclusion_probability": obj.get("posterior_inclusion_probability"),
            "coefficient_stddev": obj.get("coefficient_stddev"),
            "power": obj.get("power"),
            "significant": obj.get("significant"),
            "standard_error": obj.get("standard_error"),
            "z_score": obj.get("z_score"),
            "credible_set_min_r2": obj.get("credible_set_min_r2"),
            "method": obj.get("method"),
            "crispr_modality": obj.get("crispr_modality"),
            "source": obj.get("source"),
            "source_url": obj.get("source_url"),
            "label": obj.get("label"),
            "p_value": obj.get("p_value"),
            "chr": obj.get("chr"),
            "biological_context": obj.get("biological_context"),
            "biosample_term": obj.get("biosample_term"),
            "study": GenesFromVariantsStudy.from_dict(obj["study"]) if obj.get("study") is not None else None,
            "name": obj.get("name"),
            "class": obj.get("class"),
            "files_filesets": obj.get("files_filesets")
        })
        return _obj


