# coding: utf-8

"""
    IGVF Catalog

    IGVF Catalog OpenAPI compliant REST API built using tRPC with Express.  Our database uses 0-based, half-open coordinates for genomic coordinates in the GRCh38 (human) and GRCm39 (mouse) reference genomes.  Data is licensed under the <a href=https://creativecommons.org/licenses/by/4.0/ target=\"_blank\">Creative Commons license</a> and the software is licensed under the <a href=https://spdx.org/licenses/MIT.html target=\"_blank\">MIT license</a>.

    The version of the OpenAPI document: 1.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from igvf_catalog_client.models.diseases_from_genes_gene import DiseasesFromGenesGene
from igvf_catalog_client.models.genes_from_pathways_pathway import GenesFromPathwaysPathway
from typing import Optional, Set
from typing_extensions import Self

class GenesFromPathways(BaseModel):
    """
    GenesFromPathways
    """ # noqa: E501
    source: Optional[StrictStr] = None
    source_url: Optional[StrictStr] = None
    orgnism: Optional[StrictStr] = None
    organism: Optional[StrictStr] = None
    var_class: Optional[StrictStr] = Field(default=None, alias="class")
    method: Optional[StrictStr] = None
    label: Optional[StrictStr] = None
    files_filesets: Optional[StrictStr] = None
    gene: Optional[DiseasesFromGenesGene] = None
    pathway: Optional[GenesFromPathwaysPathway] = None
    name: StrictStr
    __properties: ClassVar[List[str]] = ["source", "source_url", "orgnism", "organism", "class", "method", "label", "files_filesets", "gene", "pathway", "name"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GenesFromPathways from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of gene
        if self.gene:
            _dict['gene'] = self.gene.to_dict()
        # override the default output from pydantic by calling `to_dict()` of pathway
        if self.pathway:
            _dict['pathway'] = self.pathway.to_dict()
        # set to None if method (nullable) is None
        # and model_fields_set contains the field
        if self.method is None and "method" in self.model_fields_set:
            _dict['method'] = None

        # set to None if label (nullable) is None
        # and model_fields_set contains the field
        if self.label is None and "label" in self.model_fields_set:
            _dict['label'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GenesFromPathways from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "source": obj.get("source"),
            "source_url": obj.get("source_url"),
            "orgnism": obj.get("orgnism"),
            "organism": obj.get("organism"),
            "class": obj.get("class"),
            "method": obj.get("method"),
            "label": obj.get("label"),
            "files_filesets": obj.get("files_filesets"),
            "gene": DiseasesFromGenesGene.from_dict(obj["gene"]) if obj.get("gene") is not None else None,
            "pathway": GenesFromPathwaysPathway.from_dict(obj["pathway"]) if obj.get("pathway") is not None else None,
            "name": obj.get("name")
        })
        return _obj


