# coding: utf-8

"""
    IGVF Catalog

    IGVF Catalog OpenAPI compliant REST API built using tRPC with Express.  Our database uses 0-based, half-open coordinates for genomic coordinates in the GRCh38 (human) and GRCm39 (mouse) reference genomes.  Data is licensed under the <a href=https://creativecommons.org/licenses/by/4.0/ target=\"_blank\">Creative Commons license</a> and the software is licensed under the <a href=https://spdx.org/licenses/MIT.html target=\"_blank\">MIT license</a>.

    The version of the OpenAPI document: 1.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from igvf_catalog_client.models.genes_genes_gene1 import GenesGenesGene1
from typing import Optional, Set
from typing_extensions import Self

class GenesGenes(BaseModel):
    """
    GenesGenes
    """ # noqa: E501
    id: StrictStr = Field(alias="_id")
    gene_1: GenesGenesGene1
    gene_2: GenesGenesGene1
    z_score: Optional[Union[StrictFloat, StrictInt]] = None
    associated_process: Optional[StrictStr] = None
    detection_method: Optional[StrictStr] = None
    detection_method_code: Optional[StrictStr] = None
    interaction_type: Optional[List[StrictStr]] = None
    interaction_type_code: Optional[List[StrictStr]] = None
    confidence_value_biogrid: Optional[Union[StrictFloat, StrictInt]] = None
    confidence_value_intact: Optional[Union[StrictFloat, StrictInt]] = None
    pmids: Optional[List[StrictStr]] = None
    label: StrictStr
    method: StrictStr
    var_class: StrictStr = Field(alias="class")
    source: StrictStr
    source_url: Optional[StrictStr] = None
    name: StrictStr
    files_filesets: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["_id", "gene_1", "gene_2", "z_score", "associated_process", "detection_method", "detection_method_code", "interaction_type", "interaction_type_code", "confidence_value_biogrid", "confidence_value_intact", "pmids", "label", "method", "class", "source", "source_url", "name", "files_filesets"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GenesGenes from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of gene_1
        if self.gene_1:
            _dict['gene_1'] = self.gene_1.to_dict()
        # override the default output from pydantic by calling `to_dict()` of gene_2
        if self.gene_2:
            _dict['gene_2'] = self.gene_2.to_dict()
        # set to None if associated_process (nullable) is None
        # and model_fields_set contains the field
        if self.associated_process is None and "associated_process" in self.model_fields_set:
            _dict['associated_process'] = None

        # set to None if confidence_value_biogrid (nullable) is None
        # and model_fields_set contains the field
        if self.confidence_value_biogrid is None and "confidence_value_biogrid" in self.model_fields_set:
            _dict['confidence_value_biogrid'] = None

        # set to None if confidence_value_intact (nullable) is None
        # and model_fields_set contains the field
        if self.confidence_value_intact is None and "confidence_value_intact" in self.model_fields_set:
            _dict['confidence_value_intact'] = None

        # set to None if files_filesets (nullable) is None
        # and model_fields_set contains the field
        if self.files_filesets is None and "files_filesets" in self.model_fields_set:
            _dict['files_filesets'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GenesGenes from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "_id": obj.get("_id"),
            "gene_1": GenesGenesGene1.from_dict(obj["gene_1"]) if obj.get("gene_1") is not None else None,
            "gene_2": GenesGenesGene1.from_dict(obj["gene_2"]) if obj.get("gene_2") is not None else None,
            "z_score": obj.get("z_score"),
            "associated_process": obj.get("associated_process"),
            "detection_method": obj.get("detection_method"),
            "detection_method_code": obj.get("detection_method_code"),
            "interaction_type": obj.get("interaction_type"),
            "interaction_type_code": obj.get("interaction_type_code"),
            "confidence_value_biogrid": obj.get("confidence_value_biogrid"),
            "confidence_value_intact": obj.get("confidence_value_intact"),
            "pmids": obj.get("pmids"),
            "label": obj.get("label"),
            "method": obj.get("method"),
            "class": obj.get("class"),
            "source": obj.get("source"),
            "source_url": obj.get("source_url"),
            "name": obj.get("name"),
            "files_filesets": obj.get("files_filesets")
        })
        return _obj


