# coding: utf-8

"""
    IGVF Catalog

    IGVF Catalog OpenAPI compliant REST API built using tRPC with Express.  Our database uses 0-based, half-open coordinates for genomic coordinates in the GRCh38 (human) and GRCm39 (mouse) reference genomes.  Data is licensed under the <a href=https://creativecommons.org/licenses/by/4.0/ target=\"_blank\">Creative Commons license</a> and the software is licensed under the <a href=https://spdx.org/licenses/MIT.html target=\"_blank\">MIT license</a>.

    The version of the OpenAPI document: 1.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from igvf_catalog_client.models.genes_from_genomic_elements_p_value import GenesFromGenomicElementsPValue
from igvf_catalog_client.models.genomic_element4 import GenomicElement4
from typing import Optional, Set
from typing_extensions import Self

class Grn(BaseModel):
    """
    Grn
    """ # noqa: E501
    response_gene: StrictStr
    genomic_element: GenomicElement4
    crispr_modality: Optional[StrictStr] = None
    var_class: StrictStr = Field(alias="class")
    method: StrictStr
    source: StrictStr
    biological_context: StrictStr
    files_filesets: StrictStr
    log2_fc: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="log2FC")
    neg_log10_pvalue: Optional[GenesFromGenomicElementsPValue] = None
    neg_log10_pvalue_adj: Optional[GenesFromGenomicElementsPValue] = None
    significant: Optional[StrictBool] = None
    perturbation_efficiency_log2_fc: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="perturbation_efficiency_log2FC")
    perturbation_efficiency_neg_log10_pvalue: Optional[GenesFromGenomicElementsPValue] = None
    perturbation_efficiency_neg_log10_pvalue_adj: Optional[GenesFromGenomicElementsPValue] = None
    perturbation_efficiency_significant: Optional[StrictBool] = None
    __properties: ClassVar[List[str]] = ["response_gene", "genomic_element", "crispr_modality", "class", "method", "source", "biological_context", "files_filesets", "log2FC", "neg_log10_pvalue", "neg_log10_pvalue_adj", "significant", "perturbation_efficiency_log2FC", "perturbation_efficiency_neg_log10_pvalue", "perturbation_efficiency_neg_log10_pvalue_adj", "perturbation_efficiency_significant"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Grn from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of genomic_element
        if self.genomic_element:
            _dict['genomic_element'] = self.genomic_element.to_dict()
        # override the default output from pydantic by calling `to_dict()` of neg_log10_pvalue
        if self.neg_log10_pvalue:
            _dict['neg_log10_pvalue'] = self.neg_log10_pvalue.to_dict()
        # override the default output from pydantic by calling `to_dict()` of neg_log10_pvalue_adj
        if self.neg_log10_pvalue_adj:
            _dict['neg_log10_pvalue_adj'] = self.neg_log10_pvalue_adj.to_dict()
        # override the default output from pydantic by calling `to_dict()` of perturbation_efficiency_neg_log10_pvalue
        if self.perturbation_efficiency_neg_log10_pvalue:
            _dict['perturbation_efficiency_neg_log10_pvalue'] = self.perturbation_efficiency_neg_log10_pvalue.to_dict()
        # override the default output from pydantic by calling `to_dict()` of perturbation_efficiency_neg_log10_pvalue_adj
        if self.perturbation_efficiency_neg_log10_pvalue_adj:
            _dict['perturbation_efficiency_neg_log10_pvalue_adj'] = self.perturbation_efficiency_neg_log10_pvalue_adj.to_dict()
        # set to None if crispr_modality (nullable) is None
        # and model_fields_set contains the field
        if self.crispr_modality is None and "crispr_modality" in self.model_fields_set:
            _dict['crispr_modality'] = None

        # set to None if log2_fc (nullable) is None
        # and model_fields_set contains the field
        if self.log2_fc is None and "log2_fc" in self.model_fields_set:
            _dict['log2FC'] = None

        # set to None if neg_log10_pvalue (nullable) is None
        # and model_fields_set contains the field
        if self.neg_log10_pvalue is None and "neg_log10_pvalue" in self.model_fields_set:
            _dict['neg_log10_pvalue'] = None

        # set to None if neg_log10_pvalue_adj (nullable) is None
        # and model_fields_set contains the field
        if self.neg_log10_pvalue_adj is None and "neg_log10_pvalue_adj" in self.model_fields_set:
            _dict['neg_log10_pvalue_adj'] = None

        # set to None if significant (nullable) is None
        # and model_fields_set contains the field
        if self.significant is None and "significant" in self.model_fields_set:
            _dict['significant'] = None

        # set to None if perturbation_efficiency_log2_fc (nullable) is None
        # and model_fields_set contains the field
        if self.perturbation_efficiency_log2_fc is None and "perturbation_efficiency_log2_fc" in self.model_fields_set:
            _dict['perturbation_efficiency_log2FC'] = None

        # set to None if perturbation_efficiency_neg_log10_pvalue (nullable) is None
        # and model_fields_set contains the field
        if self.perturbation_efficiency_neg_log10_pvalue is None and "perturbation_efficiency_neg_log10_pvalue" in self.model_fields_set:
            _dict['perturbation_efficiency_neg_log10_pvalue'] = None

        # set to None if perturbation_efficiency_neg_log10_pvalue_adj (nullable) is None
        # and model_fields_set contains the field
        if self.perturbation_efficiency_neg_log10_pvalue_adj is None and "perturbation_efficiency_neg_log10_pvalue_adj" in self.model_fields_set:
            _dict['perturbation_efficiency_neg_log10_pvalue_adj'] = None

        # set to None if perturbation_efficiency_significant (nullable) is None
        # and model_fields_set contains the field
        if self.perturbation_efficiency_significant is None and "perturbation_efficiency_significant" in self.model_fields_set:
            _dict['perturbation_efficiency_significant'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Grn from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "response_gene": obj.get("response_gene"),
            "genomic_element": GenomicElement4.from_dict(obj["genomic_element"]) if obj.get("genomic_element") is not None else None,
            "crispr_modality": obj.get("crispr_modality"),
            "class": obj.get("class"),
            "method": obj.get("method"),
            "source": obj.get("source"),
            "biological_context": obj.get("biological_context"),
            "files_filesets": obj.get("files_filesets"),
            "log2FC": obj.get("log2FC"),
            "neg_log10_pvalue": GenesFromGenomicElementsPValue.from_dict(obj["neg_log10_pvalue"]) if obj.get("neg_log10_pvalue") is not None else None,
            "neg_log10_pvalue_adj": GenesFromGenomicElementsPValue.from_dict(obj["neg_log10_pvalue_adj"]) if obj.get("neg_log10_pvalue_adj") is not None else None,
            "significant": obj.get("significant"),
            "perturbation_efficiency_log2FC": obj.get("perturbation_efficiency_log2FC"),
            "perturbation_efficiency_neg_log10_pvalue": GenesFromGenomicElementsPValue.from_dict(obj["perturbation_efficiency_neg_log10_pvalue"]) if obj.get("perturbation_efficiency_neg_log10_pvalue") is not None else None,
            "perturbation_efficiency_neg_log10_pvalue_adj": GenesFromGenomicElementsPValue.from_dict(obj["perturbation_efficiency_neg_log10_pvalue_adj"]) if obj.get("perturbation_efficiency_neg_log10_pvalue_adj") is not None else None,
            "perturbation_efficiency_significant": obj.get("perturbation_efficiency_significant")
        })
        return _obj


