# coding: utf-8

"""
    IGVF Catalog

    IGVF Catalog OpenAPI compliant REST API built using tRPC with Express.  Our database uses 0-based, half-open coordinates for genomic coordinates in the GRCh38 (human) and GRCm39 (mouse) reference genomes.  Data is licensed under the <a href=https://creativecommons.org/licenses/by/4.0/ target=\"_blank\">Creative Commons license</a> and the software is licensed under the <a href=https://spdx.org/licenses/MIT.html target=\"_blank\">MIT license</a>.

    The version of the OpenAPI document: 1.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from igvf_catalog_client.models.motifs_from_proteins200_response_inner_complex import MotifsFromProteins200ResponseInnerComplex
from igvf_catalog_client.models.motifs_from_proteins200_response_inner_motif import MotifsFromProteins200ResponseInnerMotif
from igvf_catalog_client.models.proteins_from_genes200_response_inner_protein import ProteinsFromGenes200ResponseInnerProtein
from typing import Optional, Set
from typing_extensions import Self

class MotifsFromProteins200ResponseInner(BaseModel):
    """
    MotifsFromProteins200ResponseInner
    """ # noqa: E501
    source: Optional[StrictStr] = None
    protein: Optional[ProteinsFromGenes200ResponseInnerProtein] = None
    complex: Optional[MotifsFromProteins200ResponseInnerComplex] = None
    motif: Optional[MotifsFromProteins200ResponseInnerMotif] = None
    name: StrictStr
    var_class: Optional[StrictStr] = Field(default=None, alias="class")
    method: Optional[StrictStr] = None
    files_filesets: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["source", "protein", "complex", "motif", "name", "class", "method", "files_filesets"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of MotifsFromProteins200ResponseInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of protein
        if self.protein:
            _dict['protein'] = self.protein.to_dict()
        # override the default output from pydantic by calling `to_dict()` of complex
        if self.complex:
            _dict['complex'] = self.complex.to_dict()
        # override the default output from pydantic by calling `to_dict()` of motif
        if self.motif:
            _dict['motif'] = self.motif.to_dict()
        # set to None if var_class (nullable) is None
        # and model_fields_set contains the field
        if self.var_class is None and "var_class" in self.model_fields_set:
            _dict['class'] = None

        # set to None if method (nullable) is None
        # and model_fields_set contains the field
        if self.method is None and "method" in self.model_fields_set:
            _dict['method'] = None

        # set to None if files_filesets (nullable) is None
        # and model_fields_set contains the field
        if self.files_filesets is None and "files_filesets" in self.model_fields_set:
            _dict['files_filesets'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of MotifsFromProteins200ResponseInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "source": obj.get("source"),
            "protein": ProteinsFromGenes200ResponseInnerProtein.from_dict(obj["protein"]) if obj.get("protein") is not None else None,
            "complex": MotifsFromProteins200ResponseInnerComplex.from_dict(obj["complex"]) if obj.get("complex") is not None else None,
            "motif": MotifsFromProteins200ResponseInnerMotif.from_dict(obj["motif"]) if obj.get("motif") is not None else None,
            "name": obj.get("name"),
            "class": obj.get("class"),
            "method": obj.get("method"),
            "files_filesets": obj.get("files_filesets")
        })
        return _obj


