# coding: utf-8

"""
    IGVF Catalog

    IGVF Catalog OpenAPI compliant REST API built using tRPC with Express.  Our database uses 0-based, half-open coordinates for genomic coordinates in the GRCh38 (human) and GRCm39 (mouse) reference genomes.  Data is licensed under the <a href=https://creativecommons.org/licenses/by/4.0/ target=\"_blank\">Creative Commons license</a> and the software is licensed under the <a href=https://spdx.org/licenses/MIT.html target=\"_blank\">MIT license</a>.

    The version of the OpenAPI document: 1.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from igvf_catalog_client.models.phenotypes_from_variants200_response_inner_any_of_study import PhenotypesFromVariants200ResponseInnerAnyOfStudy
from igvf_catalog_client.models.proteins_from_variants200_response_inner_sequence_variant import ProteinsFromVariants200ResponseInnerSequenceVariant
from typing import Optional, Set
from typing_extensions import Self

class PhenotypesFromVariants200ResponseInnerAnyOf(BaseModel):
    """
    PhenotypesFromVariants200ResponseInnerAnyOf
    """ # noqa: E501
    rsid: Optional[List[StrictStr]] = None
    phenotype_id: Optional[StrictStr]
    phenotype_term: Optional[StrictStr]
    study: Optional[PhenotypesFromVariants200ResponseInnerAnyOfStudy] = None
    neg_log10_pvalue: Optional[Union[StrictFloat, StrictInt]] = None
    p_value: Optional[Union[StrictFloat, StrictInt]]
    beta: Optional[Union[StrictFloat, StrictInt]]
    beta_ci_lower: Optional[Union[StrictFloat, StrictInt]]
    beta_ci_upper: Optional[Union[StrictFloat, StrictInt]]
    oddsr_ci_lower: Optional[Union[StrictFloat, StrictInt]]
    oddsr_ci_upper: Optional[Union[StrictFloat, StrictInt]]
    lead_chrom: Optional[StrictStr]
    lead_pos: Optional[Union[StrictFloat, StrictInt]]
    lead_ref: Optional[StrictStr]
    lead_alt: Optional[StrictStr]
    direction: Optional[StrictStr]
    source: StrictStr
    source_url: Optional[StrictStr] = None
    var_class: Optional[StrictStr] = Field(default=None, alias="class")
    method: Optional[StrictStr] = None
    label: Optional[StrictStr] = None
    version: Optional[StrictStr] = 'October 2022 (22.10)'
    name: StrictStr
    variant: ProteinsFromVariants200ResponseInnerSequenceVariant
    files_filesets: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["rsid", "phenotype_id", "phenotype_term", "study", "neg_log10_pvalue", "p_value", "beta", "beta_ci_lower", "beta_ci_upper", "oddsr_ci_lower", "oddsr_ci_upper", "lead_chrom", "lead_pos", "lead_ref", "lead_alt", "direction", "source", "source_url", "class", "method", "label", "version", "name", "variant", "files_filesets"]

    @field_validator('source')
    def source_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['OpenTargets']):
            raise ValueError("must be one of enum values ('OpenTargets')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PhenotypesFromVariants200ResponseInnerAnyOf from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of study
        if self.study:
            _dict['study'] = self.study.to_dict()
        # override the default output from pydantic by calling `to_dict()` of variant
        if self.variant:
            _dict['variant'] = self.variant.to_dict()
        # set to None if rsid (nullable) is None
        # and model_fields_set contains the field
        if self.rsid is None and "rsid" in self.model_fields_set:
            _dict['rsid'] = None

        # set to None if phenotype_id (nullable) is None
        # and model_fields_set contains the field
        if self.phenotype_id is None and "phenotype_id" in self.model_fields_set:
            _dict['phenotype_id'] = None

        # set to None if phenotype_term (nullable) is None
        # and model_fields_set contains the field
        if self.phenotype_term is None and "phenotype_term" in self.model_fields_set:
            _dict['phenotype_term'] = None

        # set to None if neg_log10_pvalue (nullable) is None
        # and model_fields_set contains the field
        if self.neg_log10_pvalue is None and "neg_log10_pvalue" in self.model_fields_set:
            _dict['neg_log10_pvalue'] = None

        # set to None if p_value (nullable) is None
        # and model_fields_set contains the field
        if self.p_value is None and "p_value" in self.model_fields_set:
            _dict['p_value'] = None

        # set to None if beta (nullable) is None
        # and model_fields_set contains the field
        if self.beta is None and "beta" in self.model_fields_set:
            _dict['beta'] = None

        # set to None if beta_ci_lower (nullable) is None
        # and model_fields_set contains the field
        if self.beta_ci_lower is None and "beta_ci_lower" in self.model_fields_set:
            _dict['beta_ci_lower'] = None

        # set to None if beta_ci_upper (nullable) is None
        # and model_fields_set contains the field
        if self.beta_ci_upper is None and "beta_ci_upper" in self.model_fields_set:
            _dict['beta_ci_upper'] = None

        # set to None if oddsr_ci_lower (nullable) is None
        # and model_fields_set contains the field
        if self.oddsr_ci_lower is None and "oddsr_ci_lower" in self.model_fields_set:
            _dict['oddsr_ci_lower'] = None

        # set to None if oddsr_ci_upper (nullable) is None
        # and model_fields_set contains the field
        if self.oddsr_ci_upper is None and "oddsr_ci_upper" in self.model_fields_set:
            _dict['oddsr_ci_upper'] = None

        # set to None if lead_chrom (nullable) is None
        # and model_fields_set contains the field
        if self.lead_chrom is None and "lead_chrom" in self.model_fields_set:
            _dict['lead_chrom'] = None

        # set to None if lead_pos (nullable) is None
        # and model_fields_set contains the field
        if self.lead_pos is None and "lead_pos" in self.model_fields_set:
            _dict['lead_pos'] = None

        # set to None if lead_ref (nullable) is None
        # and model_fields_set contains the field
        if self.lead_ref is None and "lead_ref" in self.model_fields_set:
            _dict['lead_ref'] = None

        # set to None if lead_alt (nullable) is None
        # and model_fields_set contains the field
        if self.lead_alt is None and "lead_alt" in self.model_fields_set:
            _dict['lead_alt'] = None

        # set to None if direction (nullable) is None
        # and model_fields_set contains the field
        if self.direction is None and "direction" in self.model_fields_set:
            _dict['direction'] = None

        # set to None if source_url (nullable) is None
        # and model_fields_set contains the field
        if self.source_url is None and "source_url" in self.model_fields_set:
            _dict['source_url'] = None

        # set to None if var_class (nullable) is None
        # and model_fields_set contains the field
        if self.var_class is None and "var_class" in self.model_fields_set:
            _dict['class'] = None

        # set to None if method (nullable) is None
        # and model_fields_set contains the field
        if self.method is None and "method" in self.model_fields_set:
            _dict['method'] = None

        # set to None if label (nullable) is None
        # and model_fields_set contains the field
        if self.label is None and "label" in self.model_fields_set:
            _dict['label'] = None

        # set to None if files_filesets (nullable) is None
        # and model_fields_set contains the field
        if self.files_filesets is None and "files_filesets" in self.model_fields_set:
            _dict['files_filesets'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PhenotypesFromVariants200ResponseInnerAnyOf from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "rsid": obj.get("rsid"),
            "phenotype_id": obj.get("phenotype_id"),
            "phenotype_term": obj.get("phenotype_term"),
            "study": PhenotypesFromVariants200ResponseInnerAnyOfStudy.from_dict(obj["study"]) if obj.get("study") is not None else None,
            "neg_log10_pvalue": obj.get("neg_log10_pvalue"),
            "p_value": obj.get("p_value"),
            "beta": obj.get("beta"),
            "beta_ci_lower": obj.get("beta_ci_lower"),
            "beta_ci_upper": obj.get("beta_ci_upper"),
            "oddsr_ci_lower": obj.get("oddsr_ci_lower"),
            "oddsr_ci_upper": obj.get("oddsr_ci_upper"),
            "lead_chrom": obj.get("lead_chrom"),
            "lead_pos": obj.get("lead_pos"),
            "lead_ref": obj.get("lead_ref"),
            "lead_alt": obj.get("lead_alt"),
            "direction": obj.get("direction"),
            "source": obj.get("source"),
            "source_url": obj.get("source_url"),
            "class": obj.get("class"),
            "method": obj.get("method"),
            "label": obj.get("label"),
            "version": obj.get("version") if obj.get("version") is not None else 'October 2022 (22.10)',
            "name": obj.get("name"),
            "variant": ProteinsFromVariants200ResponseInnerSequenceVariant.from_dict(obj["variant"]) if obj.get("variant") is not None else None,
            "files_filesets": obj.get("files_filesets")
        })
        return _obj


