# coding: utf-8

"""
    IGVF Catalog

    IGVF Catalog OpenAPI compliant REST API built using tRPC with Express.  Our database uses 0-based, half-open coordinates for genomic coordinates in the GRCh38 (human) and GRCm39 (mouse) reference genomes.  Data is licensed under the <a href=https://creativecommons.org/licenses/by/4.0/ target=\"_blank\">Creative Commons license</a> and the software is licensed under the <a href=https://spdx.org/licenses/MIT.html target=\"_blank\">MIT license</a>.

    The version of the OpenAPI document: 1.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict
from typing import Any, ClassVar, Dict, List, Optional
from igvf_catalog_client.models.qtls3 import Qtls3
from igvf_catalog_client.models.tf_binding import TfBinding
from typing import Optional, Set
from typing_extensions import Self

class Predictions2(BaseModel):
    """
    Predictions2
    """ # noqa: E501
    qtls: Optional[List[Qtls3]] = None
    tf_binding: Optional[List[TfBinding]] = None
    __properties: ClassVar[List[str]] = ["qtls", "tf_binding"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Predictions2 from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in qtls (list)
        _items = []
        if self.qtls:
            for _item_qtls in self.qtls:
                if _item_qtls:
                    _items.append(_item_qtls.to_dict())
            _dict['qtls'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in tf_binding (list)
        _items = []
        if self.tf_binding:
            for _item_tf_binding in self.tf_binding:
                if _item_tf_binding:
                    _items.append(_item_tf_binding.to_dict())
            _dict['tf_binding'] = _items
        # set to None if qtls (nullable) is None
        # and model_fields_set contains the field
        if self.qtls is None and "qtls" in self.model_fields_set:
            _dict['qtls'] = None

        # set to None if tf_binding (nullable) is None
        # and model_fields_set contains the field
        if self.tf_binding is None and "tf_binding" in self.model_fields_set:
            _dict['tf_binding'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Predictions2 from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "qtls": [Qtls3.from_dict(_item) for _item in obj["qtls"]] if obj.get("qtls") is not None else None,
            "tf_binding": [TfBinding.from_dict(_item) for _item in obj["tf_binding"]] if obj.get("tf_binding") is not None else None
        })
        return _obj


