# coding: utf-8

"""
    IGVF Catalog

    IGVF Catalog OpenAPI compliant REST API built using tRPC with Express.  Our database uses 0-based, half-open coordinates for genomic coordinates in the GRCh38 (human) and GRCm39 (mouse) reference genomes.  Data is licensed under the <a href=https://creativecommons.org/licenses/by/4.0/ target=\"_blank\">Creative Commons license</a> and the software is licensed under the <a href=https://spdx.org/licenses/MIT.html target=\"_blank\">MIT license</a>.

    The version of the OpenAPI document: 1.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from igvf_catalog_client.models.phenotypes_from_variants_variant import PhenotypesFromVariantsVariant
from igvf_catalog_client.models.proteins_from_variants_biosample_term import ProteinsFromVariantsBiosampleTerm
from igvf_catalog_client.models.proteins_from_variants_protein_complex import ProteinsFromVariantsProteinComplex
from typing import Optional, Set
from typing_extensions import Self

class ProteinsFromVariants(BaseModel):
    """
    ProteinsFromVariants
    """ # noqa: E501
    sequence_variant: Optional[PhenotypesFromVariantsVariant] = None
    protein_complex: Optional[ProteinsFromVariantsProteinComplex] = None
    biosample_term: Optional[ProteinsFromVariantsBiosampleTerm] = None
    biological_context: Optional[StrictStr] = None
    regulatory_type: Optional[StrictStr] = None
    var_class: Optional[StrictStr] = Field(default=None, alias="class")
    label: Optional[StrictStr] = None
    name: StrictStr
    method: Optional[StrictStr] = None
    files_filesets: Optional[StrictStr] = None
    source: Optional[StrictStr] = None
    source_url: Optional[StrictStr] = None
    is_complex: StrictBool
    score: Optional[Union[StrictFloat, StrictInt]] = None
    neg_log10_pvalue_adj_ref: Optional[Union[StrictFloat, StrictInt]] = None
    neg_log10_pvalue_adj_alt: Optional[Union[StrictFloat, StrictInt]] = None
    motif: Optional[StrictStr] = None
    motif_log2_fc: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="motif_log2FC")
    beta: Optional[Union[StrictFloat, StrictInt]] = None
    se: Optional[Union[StrictFloat, StrictInt]] = None
    gene: Optional[StrictStr] = None
    gene_consequence: Optional[StrictStr] = None
    neg_log10_pvalue: Optional[Union[StrictFloat, StrictInt]] = None
    p_value: Optional[Union[StrictFloat, StrictInt]] = None
    neg_log10_pvalue_adj: Optional[Union[StrictFloat, StrictInt]] = None
    variant_effect_score: Optional[Union[StrictFloat, StrictInt]] = None
    se_mpl_annotation: Optional[StrictStr] = Field(default=None, alias="SEMpl_annotation")
    se_mpl_baseline: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="SEMpl_baseline")
    alt_score: Optional[Union[StrictFloat, StrictInt]] = None
    ref_score: Optional[Union[StrictFloat, StrictInt]] = None
    relative_binding_affinity: Optional[Union[StrictFloat, StrictInt]] = None
    effect_on_binding: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["sequence_variant", "protein_complex", "biosample_term", "biological_context", "regulatory_type", "class", "label", "name", "method", "files_filesets", "source", "source_url", "is_complex", "score", "neg_log10_pvalue_adj_ref", "neg_log10_pvalue_adj_alt", "motif", "motif_log2FC", "beta", "se", "gene", "gene_consequence", "neg_log10_pvalue", "p_value", "neg_log10_pvalue_adj", "variant_effect_score", "SEMpl_annotation", "SEMpl_baseline", "alt_score", "ref_score", "relative_binding_affinity", "effect_on_binding"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ProteinsFromVariants from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of sequence_variant
        if self.sequence_variant:
            _dict['sequence_variant'] = self.sequence_variant.to_dict()
        # override the default output from pydantic by calling `to_dict()` of protein_complex
        if self.protein_complex:
            _dict['protein_complex'] = self.protein_complex.to_dict()
        # override the default output from pydantic by calling `to_dict()` of biosample_term
        if self.biosample_term:
            _dict['biosample_term'] = self.biosample_term.to_dict()
        # set to None if biosample_term (nullable) is None
        # and model_fields_set contains the field
        if self.biosample_term is None and "biosample_term" in self.model_fields_set:
            _dict['biosample_term'] = None

        # set to None if biological_context (nullable) is None
        # and model_fields_set contains the field
        if self.biological_context is None and "biological_context" in self.model_fields_set:
            _dict['biological_context'] = None

        # set to None if regulatory_type (nullable) is None
        # and model_fields_set contains the field
        if self.regulatory_type is None and "regulatory_type" in self.model_fields_set:
            _dict['regulatory_type'] = None

        # set to None if var_class (nullable) is None
        # and model_fields_set contains the field
        if self.var_class is None and "var_class" in self.model_fields_set:
            _dict['class'] = None

        # set to None if label (nullable) is None
        # and model_fields_set contains the field
        if self.label is None and "label" in self.model_fields_set:
            _dict['label'] = None

        # set to None if method (nullable) is None
        # and model_fields_set contains the field
        if self.method is None and "method" in self.model_fields_set:
            _dict['method'] = None

        # set to None if files_filesets (nullable) is None
        # and model_fields_set contains the field
        if self.files_filesets is None and "files_filesets" in self.model_fields_set:
            _dict['files_filesets'] = None

        # set to None if source (nullable) is None
        # and model_fields_set contains the field
        if self.source is None and "source" in self.model_fields_set:
            _dict['source'] = None

        # set to None if source_url (nullable) is None
        # and model_fields_set contains the field
        if self.source_url is None and "source_url" in self.model_fields_set:
            _dict['source_url'] = None

        # set to None if score (nullable) is None
        # and model_fields_set contains the field
        if self.score is None and "score" in self.model_fields_set:
            _dict['score'] = None

        # set to None if neg_log10_pvalue_adj_ref (nullable) is None
        # and model_fields_set contains the field
        if self.neg_log10_pvalue_adj_ref is None and "neg_log10_pvalue_adj_ref" in self.model_fields_set:
            _dict['neg_log10_pvalue_adj_ref'] = None

        # set to None if neg_log10_pvalue_adj_alt (nullable) is None
        # and model_fields_set contains the field
        if self.neg_log10_pvalue_adj_alt is None and "neg_log10_pvalue_adj_alt" in self.model_fields_set:
            _dict['neg_log10_pvalue_adj_alt'] = None

        # set to None if motif (nullable) is None
        # and model_fields_set contains the field
        if self.motif is None and "motif" in self.model_fields_set:
            _dict['motif'] = None

        # set to None if motif_log2_fc (nullable) is None
        # and model_fields_set contains the field
        if self.motif_log2_fc is None and "motif_log2_fc" in self.model_fields_set:
            _dict['motif_log2FC'] = None

        # set to None if beta (nullable) is None
        # and model_fields_set contains the field
        if self.beta is None and "beta" in self.model_fields_set:
            _dict['beta'] = None

        # set to None if se (nullable) is None
        # and model_fields_set contains the field
        if self.se is None and "se" in self.model_fields_set:
            _dict['se'] = None

        # set to None if gene (nullable) is None
        # and model_fields_set contains the field
        if self.gene is None and "gene" in self.model_fields_set:
            _dict['gene'] = None

        # set to None if gene_consequence (nullable) is None
        # and model_fields_set contains the field
        if self.gene_consequence is None and "gene_consequence" in self.model_fields_set:
            _dict['gene_consequence'] = None

        # set to None if neg_log10_pvalue (nullable) is None
        # and model_fields_set contains the field
        if self.neg_log10_pvalue is None and "neg_log10_pvalue" in self.model_fields_set:
            _dict['neg_log10_pvalue'] = None

        # set to None if p_value (nullable) is None
        # and model_fields_set contains the field
        if self.p_value is None and "p_value" in self.model_fields_set:
            _dict['p_value'] = None

        # set to None if neg_log10_pvalue_adj (nullable) is None
        # and model_fields_set contains the field
        if self.neg_log10_pvalue_adj is None and "neg_log10_pvalue_adj" in self.model_fields_set:
            _dict['neg_log10_pvalue_adj'] = None

        # set to None if variant_effect_score (nullable) is None
        # and model_fields_set contains the field
        if self.variant_effect_score is None and "variant_effect_score" in self.model_fields_set:
            _dict['variant_effect_score'] = None

        # set to None if se_mpl_annotation (nullable) is None
        # and model_fields_set contains the field
        if self.se_mpl_annotation is None and "se_mpl_annotation" in self.model_fields_set:
            _dict['SEMpl_annotation'] = None

        # set to None if se_mpl_baseline (nullable) is None
        # and model_fields_set contains the field
        if self.se_mpl_baseline is None and "se_mpl_baseline" in self.model_fields_set:
            _dict['SEMpl_baseline'] = None

        # set to None if alt_score (nullable) is None
        # and model_fields_set contains the field
        if self.alt_score is None and "alt_score" in self.model_fields_set:
            _dict['alt_score'] = None

        # set to None if ref_score (nullable) is None
        # and model_fields_set contains the field
        if self.ref_score is None and "ref_score" in self.model_fields_set:
            _dict['ref_score'] = None

        # set to None if relative_binding_affinity (nullable) is None
        # and model_fields_set contains the field
        if self.relative_binding_affinity is None and "relative_binding_affinity" in self.model_fields_set:
            _dict['relative_binding_affinity'] = None

        # set to None if effect_on_binding (nullable) is None
        # and model_fields_set contains the field
        if self.effect_on_binding is None and "effect_on_binding" in self.model_fields_set:
            _dict['effect_on_binding'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ProteinsFromVariants from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "sequence_variant": PhenotypesFromVariantsVariant.from_dict(obj["sequence_variant"]) if obj.get("sequence_variant") is not None else None,
            "protein_complex": ProteinsFromVariantsProteinComplex.from_dict(obj["protein_complex"]) if obj.get("protein_complex") is not None else None,
            "biosample_term": ProteinsFromVariantsBiosampleTerm.from_dict(obj["biosample_term"]) if obj.get("biosample_term") is not None else None,
            "biological_context": obj.get("biological_context"),
            "regulatory_type": obj.get("regulatory_type"),
            "class": obj.get("class"),
            "label": obj.get("label"),
            "name": obj.get("name"),
            "method": obj.get("method"),
            "files_filesets": obj.get("files_filesets"),
            "source": obj.get("source"),
            "source_url": obj.get("source_url"),
            "is_complex": obj.get("is_complex"),
            "score": obj.get("score"),
            "neg_log10_pvalue_adj_ref": obj.get("neg_log10_pvalue_adj_ref"),
            "neg_log10_pvalue_adj_alt": obj.get("neg_log10_pvalue_adj_alt"),
            "motif": obj.get("motif"),
            "motif_log2FC": obj.get("motif_log2FC"),
            "beta": obj.get("beta"),
            "se": obj.get("se"),
            "gene": obj.get("gene"),
            "gene_consequence": obj.get("gene_consequence"),
            "neg_log10_pvalue": obj.get("neg_log10_pvalue"),
            "p_value": obj.get("p_value"),
            "neg_log10_pvalue_adj": obj.get("neg_log10_pvalue_adj"),
            "variant_effect_score": obj.get("variant_effect_score"),
            "SEMpl_annotation": obj.get("SEMpl_annotation"),
            "SEMpl_baseline": obj.get("SEMpl_baseline"),
            "alt_score": obj.get("alt_score"),
            "ref_score": obj.get("ref_score"),
            "relative_binding_affinity": obj.get("relative_binding_affinity"),
            "effect_on_binding": obj.get("effect_on_binding")
        })
        return _obj


