# coding: utf-8

"""
    IGVF Catalog

    IGVF Catalog OpenAPI compliant REST API built using tRPC with Express.  Our database uses 0-based, half-open coordinates for genomic coordinates in the GRCh38 (human) and GRCm39 (mouse) reference genomes.  Data is licensed under the <a href=https://creativecommons.org/licenses/by/4.0/ target=\"_blank\">Creative Commons license</a> and the software is licensed under the <a href=https://spdx.org/licenses/MIT.html target=\"_blank\">MIT license</a>.

    The version of the OpenAPI document: 1.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from igvf_catalog_client.models.genes_from_transcripts_transcript import GenesFromTranscriptsTranscript
from igvf_catalog_client.models.proteins_from_transcripts_protein import ProteinsFromTranscriptsProtein
from typing import Optional, Set
from typing_extensions import Self

class ProteinsFromTranscripts(BaseModel):
    """
    ProteinsFromTranscripts
    """ # noqa: E501
    source: Optional[StrictStr] = None
    source_url: Optional[StrictStr] = None
    protein: Optional[ProteinsFromTranscriptsProtein] = None
    transcript: Optional[GenesFromTranscriptsTranscript] = None
    name: StrictStr
    __properties: ClassVar[List[str]] = ["source", "source_url", "protein", "transcript", "name"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ProteinsFromTranscripts from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of protein
        if self.protein:
            _dict['protein'] = self.protein.to_dict()
        # override the default output from pydantic by calling `to_dict()` of transcript
        if self.transcript:
            _dict['transcript'] = self.transcript.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ProteinsFromTranscripts from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "source": obj.get("source"),
            "source_url": obj.get("source_url"),
            "protein": ProteinsFromTranscriptsProtein.from_dict(obj["protein"]) if obj.get("protein") is not None else None,
            "transcript": GenesFromTranscriptsTranscript.from_dict(obj["transcript"]) if obj.get("transcript") is not None else None,
            "name": obj.get("name")
        })
        return _obj


