# coding: utf-8

"""
    IGVF Catalog

    IGVF Catalog OpenAPI compliant REST API built using tRPC with Express.  Our database uses 0-based, half-open coordinates for genomic coordinates in the GRCh38 (human) and GRCm39 (mouse) reference genomes.  Data is licensed under the <a href=https://creativecommons.org/licenses/by/4.0/ target=\"_blank\">Creative Commons license</a> and the software is licensed under the <a href=https://spdx.org/licenses/MIT.html target=\"_blank\">MIT license</a>.

    The version of the OpenAPI document: 1.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from igvf_catalog_client.models.qtl_summary_endpoint200_response_inner_gene import QtlSummaryEndpoint200ResponseInnerGene
from typing import Optional, Set
from typing_extensions import Self

class QtlSummaryEndpoint200ResponseInner(BaseModel):
    """
    QtlSummaryEndpoint200ResponseInner
    """ # noqa: E501
    qtl_type: StrictStr
    neg_log10_pvalue: Optional[Union[StrictFloat, StrictInt]] = None
    chr: StrictStr
    biological_context: Optional[StrictStr] = None
    effect_size: Optional[Union[StrictFloat, StrictInt]] = None
    gene: Optional[QtlSummaryEndpoint200ResponseInnerGene] = None
    name: Optional[StrictStr] = None
    files_filesets: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["qtl_type", "neg_log10_pvalue", "chr", "biological_context", "effect_size", "gene", "name", "files_filesets"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of QtlSummaryEndpoint200ResponseInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of gene
        if self.gene:
            _dict['gene'] = self.gene.to_dict()
        # set to None if neg_log10_pvalue (nullable) is None
        # and model_fields_set contains the field
        if self.neg_log10_pvalue is None and "neg_log10_pvalue" in self.model_fields_set:
            _dict['neg_log10_pvalue'] = None

        # set to None if biological_context (nullable) is None
        # and model_fields_set contains the field
        if self.biological_context is None and "biological_context" in self.model_fields_set:
            _dict['biological_context'] = None

        # set to None if effect_size (nullable) is None
        # and model_fields_set contains the field
        if self.effect_size is None and "effect_size" in self.model_fields_set:
            _dict['effect_size'] = None

        # set to None if gene (nullable) is None
        # and model_fields_set contains the field
        if self.gene is None and "gene" in self.model_fields_set:
            _dict['gene'] = None

        # set to None if name (nullable) is None
        # and model_fields_set contains the field
        if self.name is None and "name" in self.model_fields_set:
            _dict['name'] = None

        # set to None if files_filesets (nullable) is None
        # and model_fields_set contains the field
        if self.files_filesets is None and "files_filesets" in self.model_fields_set:
            _dict['files_filesets'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of QtlSummaryEndpoint200ResponseInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "qtl_type": obj.get("qtl_type"),
            "neg_log10_pvalue": obj.get("neg_log10_pvalue"),
            "chr": obj.get("chr"),
            "biological_context": obj.get("biological_context"),
            "effect_size": obj.get("effect_size"),
            "gene": QtlSummaryEndpoint200ResponseInnerGene.from_dict(obj["gene"]) if obj.get("gene") is not None else None,
            "name": obj.get("name"),
            "files_filesets": obj.get("files_filesets")
        })
        return _obj


