# coding: utf-8

"""
    IGVF Catalog

    IGVF Catalog OpenAPI compliant REST API built using tRPC with Express.  Our database uses 0-based, half-open coordinates for genomic coordinates in the GRCh38 (human) and GRCm39 (mouse) reference genomes.  Data is licensed under the <a href=https://creativecommons.org/licenses/by/4.0/ target=\"_blank\">Creative Commons license</a> and the software is licensed under the <a href=https://spdx.org/licenses/MIT.html target=\"_blank\">MIT license</a>.

    The version of the OpenAPI document: 1.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class Summary(BaseModel):
    """
    Summary
    """ # noqa: E501
    rsid: Optional[List[StrictStr]] = None
    varinfo: Optional[StrictStr] = None
    spdi: Optional[StrictStr] = None
    hgvs: Optional[StrictStr] = None
    ca_id: Optional[StrictStr] = None
    ref: Optional[StrictStr] = None
    alt: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["rsid", "varinfo", "spdi", "hgvs", "ca_id", "ref", "alt"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Summary from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if rsid (nullable) is None
        # and model_fields_set contains the field
        if self.rsid is None and "rsid" in self.model_fields_set:
            _dict['rsid'] = None

        # set to None if varinfo (nullable) is None
        # and model_fields_set contains the field
        if self.varinfo is None and "varinfo" in self.model_fields_set:
            _dict['varinfo'] = None

        # set to None if spdi (nullable) is None
        # and model_fields_set contains the field
        if self.spdi is None and "spdi" in self.model_fields_set:
            _dict['spdi'] = None

        # set to None if hgvs (nullable) is None
        # and model_fields_set contains the field
        if self.hgvs is None and "hgvs" in self.model_fields_set:
            _dict['hgvs'] = None

        # set to None if ca_id (nullable) is None
        # and model_fields_set contains the field
        if self.ca_id is None and "ca_id" in self.model_fields_set:
            _dict['ca_id'] = None

        # set to None if ref (nullable) is None
        # and model_fields_set contains the field
        if self.ref is None and "ref" in self.model_fields_set:
            _dict['ref'] = None

        # set to None if alt (nullable) is None
        # and model_fields_set contains the field
        if self.alt is None and "alt" in self.model_fields_set:
            _dict['alt'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Summary from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "rsid": obj.get("rsid"),
            "varinfo": obj.get("varinfo"),
            "spdi": obj.get("spdi"),
            "hgvs": obj.get("hgvs"),
            "ca_id": obj.get("ca_id"),
            "ref": obj.get("ref"),
            "alt": obj.get("alt")
        })
        return _obj


