# coding: utf-8

"""
    IGVF Catalog

    IGVF Catalog OpenAPI compliant REST API built using tRPC with Express.  Our database uses 0-based, half-open coordinates for genomic coordinates in the GRCh38 (human) and GRCm39 (mouse) reference genomes.  Data is licensed under the <a href=https://creativecommons.org/licenses/by/4.0/ target=\"_blank\">Creative Commons license</a> and the software is licensed under the <a href=https://spdx.org/licenses/MIT.html target=\"_blank\">MIT license</a>.

    The version of the OpenAPI document: 1.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict
from typing import Any, ClassVar, Dict, List, Optional
from igvf_catalog_client.models.cadd_scores import CaddScores
from igvf_catalog_client.models.nearest_genes import NearestGenes
from igvf_catalog_client.models.summary import Summary
from typing import Optional, Set
from typing_extensions import Self

class VariantSummary(BaseModel):
    """
    VariantSummary
    """ # noqa: E501
    summary: Summary
    allele_frequencies_gnomad: Optional[Any] = None
    cadd_scores: Optional[CaddScores] = None
    nearest_genes: NearestGenes
    __properties: ClassVar[List[str]] = ["summary", "allele_frequencies_gnomad", "cadd_scores", "nearest_genes"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of VariantSummary from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of summary
        if self.summary:
            _dict['summary'] = self.summary.to_dict()
        # override the default output from pydantic by calling `to_dict()` of cadd_scores
        if self.cadd_scores:
            _dict['cadd_scores'] = self.cadd_scores.to_dict()
        # override the default output from pydantic by calling `to_dict()` of nearest_genes
        if self.nearest_genes:
            _dict['nearest_genes'] = self.nearest_genes.to_dict()
        # set to None if allele_frequencies_gnomad (nullable) is None
        # and model_fields_set contains the field
        if self.allele_frequencies_gnomad is None and "allele_frequencies_gnomad" in self.model_fields_set:
            _dict['allele_frequencies_gnomad'] = None

        # set to None if cadd_scores (nullable) is None
        # and model_fields_set contains the field
        if self.cadd_scores is None and "cadd_scores" in self.model_fields_set:
            _dict['cadd_scores'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of VariantSummary from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "summary": Summary.from_dict(obj["summary"]) if obj.get("summary") is not None else None,
            "allele_frequencies_gnomad": obj.get("allele_frequencies_gnomad"),
            "cadd_scores": CaddScores.from_dict(obj["cadd_scores"]) if obj.get("cadd_scores") is not None else None,
            "nearest_genes": NearestGenes.from_dict(obj["nearest_genes"]) if obj.get("nearest_genes") is not None else None
        })
        return _obj


