# coding: utf-8

"""
    IGVF Catalog

    IGVF Catalog OpenAPI compliant REST API built using tRPC with Express.  Our database uses 0-based, half-open coordinates for genomic coordinates in the GRCh38 (human) and GRCm39 (mouse) reference genomes.  Data is licensed under the <a href=https://creativecommons.org/licenses/by/4.0/ target=\"_blank\">Creative Commons license</a> and the software is licensed under the <a href=https://spdx.org/licenses/MIT.html target=\"_blank\">MIT license</a>.

    The version of the OpenAPI document: 1.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from igvf_catalog_client.models.proteins_from_variants200_response_inner_sequence_variant import ProteinsFromVariants200ResponseInnerSequenceVariant
from igvf_catalog_client.models.variants_from_variant_id_summary200_response_inner_predictions import VariantsFromVariantIDSummary200ResponseInnerPredictions
from typing import Optional, Set
from typing_extensions import Self

class VariantsFromVariantIDSummary200ResponseInner(BaseModel):
    """
    VariantsFromVariantIDSummary200ResponseInner
    """ # noqa: E501
    ancestry: StrictStr
    d_prime: Optional[Union[StrictFloat, StrictInt]] = None
    r2: Optional[Union[StrictFloat, StrictInt]] = None
    sequence_variant: ProteinsFromVariants200ResponseInnerSequenceVariant = Field(alias="sequence variant")
    predictions: VariantsFromVariantIDSummary200ResponseInnerPredictions
    __properties: ClassVar[List[str]] = ["ancestry", "d_prime", "r2", "sequence variant", "predictions"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of VariantsFromVariantIDSummary200ResponseInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of sequence_variant
        if self.sequence_variant:
            _dict['sequence variant'] = self.sequence_variant.to_dict()
        # override the default output from pydantic by calling `to_dict()` of predictions
        if self.predictions:
            _dict['predictions'] = self.predictions.to_dict()
        # set to None if d_prime (nullable) is None
        # and model_fields_set contains the field
        if self.d_prime is None and "d_prime" in self.model_fields_set:
            _dict['d_prime'] = None

        # set to None if r2 (nullable) is None
        # and model_fields_set contains the field
        if self.r2 is None and "r2" in self.model_fields_set:
            _dict['r2'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of VariantsFromVariantIDSummary200ResponseInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "ancestry": obj.get("ancestry"),
            "d_prime": obj.get("d_prime"),
            "r2": obj.get("r2"),
            "sequence variant": ProteinsFromVariants200ResponseInnerSequenceVariant.from_dict(obj["sequence variant"]) if obj.get("sequence variant") is not None else None,
            "predictions": VariantsFromVariantIDSummary200ResponseInnerPredictions.from_dict(obj["predictions"]) if obj.get("predictions") is not None else None
        })
        return _obj


